// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package rdbiface provides an interface to enable mocking the rdb service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package rdbiface

import (
	"github.com/tily/sdk-go/aws/request"
	"github.com/tily/sdk-go/service/rdb"
)

// rdbAPI provides an interface to enable mocking the
// rdb.rdb service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // rdb.
//    func myFunc(svc rdbiface.rdbAPI) bool {
//        // Make svc.AddSourceIdentifierToSubscription request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := rdb.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockrdbClient struct {
//        rdbiface.rdbAPI
//    }
//    func (m *mockrdbClient) AddSourceIdentifierToSubscription(input *rdb.AddSourceIdentifierToSubscriptionInput) (*rdb.AddSourceIdentifierToSubscriptionOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockrdbClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type rdbAPI interface {
	AddSourceIdentifierToSubscriptionRequest(*rdb.AddSourceIdentifierToSubscriptionInput) (*request.Request, *rdb.AddSourceIdentifierToSubscriptionOutput)

	AddSourceIdentifierToSubscription(*rdb.AddSourceIdentifierToSubscriptionInput) (*rdb.AddSourceIdentifierToSubscriptionOutput, error)

	AuthorizeDBSecurityGroupIngressRequest(*rdb.AuthorizeDBSecurityGroupIngressInput) (*request.Request, *rdb.AuthorizeDBSecurityGroupIngressOutput)

	AuthorizeDBSecurityGroupIngress(*rdb.AuthorizeDBSecurityGroupIngressInput) (*rdb.AuthorizeDBSecurityGroupIngressOutput, error)

	CopyDBSnapshotRequest(*rdb.CopyDBSnapshotInput) (*request.Request, *rdb.CopyDBSnapshotOutput)

	CopyDBSnapshot(*rdb.CopyDBSnapshotInput) (*rdb.CopyDBSnapshotOutput, error)

	CreateDBInstanceRequest(*rdb.CreateDBInstanceInput) (*request.Request, *rdb.CreateDBInstanceOutput)

	CreateDBInstance(*rdb.CreateDBInstanceInput) (*rdb.CreateDBInstanceOutput, error)

	CreateDBInstanceReadReplicaRequest(*rdb.CreateDBInstanceReadReplicaInput) (*request.Request, *rdb.CreateDBInstanceReadReplicaOutput)

	CreateDBInstanceReadReplica(*rdb.CreateDBInstanceReadReplicaInput) (*rdb.CreateDBInstanceReadReplicaOutput, error)

	CreateDBParameterGroupRequest(*rdb.CreateDBParameterGroupInput) (*request.Request, *rdb.CreateDBParameterGroupOutput)

	CreateDBParameterGroup(*rdb.CreateDBParameterGroupInput) (*rdb.CreateDBParameterGroupOutput, error)

	CreateDBSecurityGroupRequest(*rdb.CreateDBSecurityGroupInput) (*request.Request, *rdb.CreateDBSecurityGroupOutput)

	CreateDBSecurityGroup(*rdb.CreateDBSecurityGroupInput) (*rdb.CreateDBSecurityGroupOutput, error)

	CreateDBSnapshotRequest(*rdb.CreateDBSnapshotInput) (*request.Request, *rdb.CreateDBSnapshotOutput)

	CreateDBSnapshot(*rdb.CreateDBSnapshotInput) (*rdb.CreateDBSnapshotOutput, error)

	CreateEventSubscriptionRequest(*rdb.CreateEventSubscriptionInput) (*request.Request, *rdb.CreateEventSubscriptionOutput)

	CreateEventSubscription(*rdb.CreateEventSubscriptionInput) (*rdb.CreateEventSubscriptionOutput, error)

	DeleteDBInstanceRequest(*rdb.DeleteDBInstanceInput) (*request.Request, *rdb.DeleteDBInstanceOutput)

	DeleteDBInstance(*rdb.DeleteDBInstanceInput) (*rdb.DeleteDBInstanceOutput, error)

	DeleteDBParameterGroupRequest(*rdb.DeleteDBParameterGroupInput) (*request.Request, *rdb.DeleteDBParameterGroupOutput)

	DeleteDBParameterGroup(*rdb.DeleteDBParameterGroupInput) (*rdb.DeleteDBParameterGroupOutput, error)

	DeleteDBSecurityGroupRequest(*rdb.DeleteDBSecurityGroupInput) (*request.Request, *rdb.DeleteDBSecurityGroupOutput)

	DeleteDBSecurityGroup(*rdb.DeleteDBSecurityGroupInput) (*rdb.DeleteDBSecurityGroupOutput, error)

	DeleteDBSnapshotRequest(*rdb.DeleteDBSnapshotInput) (*request.Request, *rdb.DeleteDBSnapshotOutput)

	DeleteDBSnapshot(*rdb.DeleteDBSnapshotInput) (*rdb.DeleteDBSnapshotOutput, error)

	DeleteEventSubscriptionRequest(*rdb.DeleteEventSubscriptionInput) (*request.Request, *rdb.DeleteEventSubscriptionOutput)

	DeleteEventSubscription(*rdb.DeleteEventSubscriptionInput) (*rdb.DeleteEventSubscriptionOutput, error)

	DescribeDBEngineVersionsRequest(*rdb.DescribeDBEngineVersionsInput) (*request.Request, *rdb.DescribeDBEngineVersionsOutput)

	DescribeDBEngineVersions(*rdb.DescribeDBEngineVersionsInput) (*rdb.DescribeDBEngineVersionsOutput, error)

	DescribeDBInstancesRequest(*rdb.DescribeDBInstancesInput) (*request.Request, *rdb.DescribeDBInstancesOutput)

	DescribeDBInstances(*rdb.DescribeDBInstancesInput) (*rdb.DescribeDBInstancesOutput, error)

	DescribeDBLogFilesRequest(*rdb.DescribeDBLogFilesInput) (*request.Request, *rdb.DescribeDBLogFilesOutput)

	DescribeDBLogFiles(*rdb.DescribeDBLogFilesInput) (*rdb.DescribeDBLogFilesOutput, error)

	DescribeDBParameterGroupsRequest(*rdb.DescribeDBParameterGroupsInput) (*request.Request, *rdb.DescribeDBParameterGroupsOutput)

	DescribeDBParameterGroups(*rdb.DescribeDBParameterGroupsInput) (*rdb.DescribeDBParameterGroupsOutput, error)

	DescribeDBParametersRequest(*rdb.DescribeDBParametersInput) (*request.Request, *rdb.DescribeDBParametersOutput)

	DescribeDBParameters(*rdb.DescribeDBParametersInput) (*rdb.DescribeDBParametersOutput, error)

	DescribeDBSecurityGroupsRequest(*rdb.DescribeDBSecurityGroupsInput) (*request.Request, *rdb.DescribeDBSecurityGroupsOutput)

	DescribeDBSecurityGroups(*rdb.DescribeDBSecurityGroupsInput) (*rdb.DescribeDBSecurityGroupsOutput, error)

	DescribeDBSnapshotsRequest(*rdb.DescribeDBSnapshotsInput) (*request.Request, *rdb.DescribeDBSnapshotsOutput)

	DescribeDBSnapshots(*rdb.DescribeDBSnapshotsInput) (*rdb.DescribeDBSnapshotsOutput, error)

	DescribeEngineDefaultParametersRequest(*rdb.DescribeEngineDefaultParametersInput) (*request.Request, *rdb.DescribeEngineDefaultParametersOutput)

	DescribeEngineDefaultParameters(*rdb.DescribeEngineDefaultParametersInput) (*rdb.DescribeEngineDefaultParametersOutput, error)

	DescribeEventCategoriesRequest(*rdb.DescribeEventCategoriesInput) (*request.Request, *rdb.DescribeEventCategoriesOutput)

	DescribeEventCategories(*rdb.DescribeEventCategoriesInput) (*rdb.DescribeEventCategoriesOutput, error)

	DescribeEventSubscriptionsRequest(*rdb.DescribeEventSubscriptionsInput) (*request.Request, *rdb.DescribeEventSubscriptionsOutput)

	DescribeEventSubscriptions(*rdb.DescribeEventSubscriptionsInput) (*rdb.DescribeEventSubscriptionsOutput, error)

	DescribeEventsRequest(*rdb.DescribeEventsInput) (*request.Request, *rdb.DescribeEventsOutput)

	DescribeEvents(*rdb.DescribeEventsInput) (*rdb.DescribeEventsOutput, error)

	DescribeOrderableDBInstanceOptionsRequest(*rdb.DescribeOrderableDBInstanceOptionsInput) (*request.Request, *rdb.DescribeOrderableDBInstanceOptionsOutput)

	DescribeOrderableDBInstanceOptions(*rdb.DescribeOrderableDBInstanceOptionsInput) (*rdb.DescribeOrderableDBInstanceOptionsOutput, error)

	DownloadDBLogFilePortionRequest(*rdb.DownloadDBLogFilePortionInput) (*request.Request, *rdb.DownloadDBLogFilePortionOutput)

	DownloadDBLogFilePortion(*rdb.DownloadDBLogFilePortionInput) (*rdb.DownloadDBLogFilePortionOutput, error)

	ModifyDBInstanceRequest(*rdb.ModifyDBInstanceInput) (*request.Request, *rdb.ModifyDBInstanceOutput)

	ModifyDBInstance(*rdb.ModifyDBInstanceInput) (*rdb.ModifyDBInstanceOutput, error)

	ModifyDBParameterGroupRequest(*rdb.ModifyDBParameterGroupInput) (*request.Request, *rdb.ModifyDBParameterGroupOutput)

	ModifyDBParameterGroup(*rdb.ModifyDBParameterGroupInput) (*rdb.ModifyDBParameterGroupOutput, error)

	ModifyEventSubscriptionRequest(*rdb.ModifyEventSubscriptionInput) (*request.Request, *rdb.ModifyEventSubscriptionOutput)

	ModifyEventSubscription(*rdb.ModifyEventSubscriptionInput) (*rdb.ModifyEventSubscriptionOutput, error)

	NiftyFailoverDBInstanceRequest(*rdb.NiftyFailoverDBInstanceInput) (*request.Request, *rdb.NiftyFailoverDBInstanceOutput)

	NiftyFailoverDBInstance(*rdb.NiftyFailoverDBInstanceInput) (*rdb.NiftyFailoverDBInstanceOutput, error)

	NiftyGetMetricStatisticsRequest(*rdb.NiftyGetMetricStatisticsInput) (*request.Request, *rdb.NiftyGetMetricStatisticsOutput)

	NiftyGetMetricStatistics(*rdb.NiftyGetMetricStatisticsInput) (*rdb.NiftyGetMetricStatisticsOutput, error)

	RebootDBInstanceRequest(*rdb.RebootDBInstanceInput) (*request.Request, *rdb.RebootDBInstanceOutput)

	RebootDBInstance(*rdb.RebootDBInstanceInput) (*rdb.RebootDBInstanceOutput, error)

	RemoveSourceIdentifierFromSubscriptionRequest(*rdb.RemoveSourceIdentifierFromSubscriptionInput) (*request.Request, *rdb.RemoveSourceIdentifierFromSubscriptionOutput)

	RemoveSourceIdentifierFromSubscription(*rdb.RemoveSourceIdentifierFromSubscriptionInput) (*rdb.RemoveSourceIdentifierFromSubscriptionOutput, error)

	ResetDBParameterGroupRequest(*rdb.ResetDBParameterGroupInput) (*request.Request, *rdb.ResetDBParameterGroupOutput)

	ResetDBParameterGroup(*rdb.ResetDBParameterGroupInput) (*rdb.ResetDBParameterGroupOutput, error)

	RestoreDBInstanceFromDBSnapshotRequest(*rdb.RestoreDBInstanceFromDBSnapshotInput) (*request.Request, *rdb.RestoreDBInstanceFromDBSnapshotOutput)

	RestoreDBInstanceFromDBSnapshot(*rdb.RestoreDBInstanceFromDBSnapshotInput) (*rdb.RestoreDBInstanceFromDBSnapshotOutput, error)

	RestoreDBInstanceToPointInTimeRequest(*rdb.RestoreDBInstanceToPointInTimeInput) (*request.Request, *rdb.RestoreDBInstanceToPointInTimeOutput)

	RestoreDBInstanceToPointInTime(*rdb.RestoreDBInstanceToPointInTimeInput) (*rdb.RestoreDBInstanceToPointInTimeOutput, error)

	RevokeDBSecurityGroupIngressRequest(*rdb.RevokeDBSecurityGroupIngressInput) (*request.Request, *rdb.RevokeDBSecurityGroupIngressOutput)

	RevokeDBSecurityGroupIngress(*rdb.RevokeDBSecurityGroupIngressInput) (*rdb.RevokeDBSecurityGroupIngressOutput, error)
}

var _ rdbAPI = (*rdb.rdb)(nil)
