// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package storageiface provides an interface to enable mocking the storage service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package storageiface

import (
	"github.com/tily/sdk-go/aws/request"
	"github.com/tily/sdk-go/service/storage"
)

// storageAPI provides an interface to enable mocking the
// storage.storage service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // storage.
//    func myFunc(svc storageiface.storageAPI) bool {
//        // Make svc.AbortMultipartUpload request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := storage.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockstorageClient struct {
//        storageiface.storageAPI
//    }
//    func (m *mockstorageClient) AbortMultipartUpload(input *storage.AbortMultipartUploadInput) (*storage.AbortMultipartUploadOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockstorageClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type storageAPI interface {
	AbortMultipartUploadRequest(*storage.AbortMultipartUploadInput) (*request.Request, *storage.AbortMultipartUploadOutput)

	AbortMultipartUpload(*storage.AbortMultipartUploadInput) (*storage.AbortMultipartUploadOutput, error)

	CompleteMultipartUploadRequest(*storage.CompleteMultipartUploadInput) (*request.Request, *storage.CompleteMultipartUploadOutput)

	CompleteMultipartUpload(*storage.CompleteMultipartUploadInput) (*storage.CompleteMultipartUploadOutput, error)

	CopyObjectRequest(*storage.CopyObjectInput) (*request.Request, *storage.CopyObjectOutput)

	CopyObject(*storage.CopyObjectInput) (*storage.CopyObjectOutput, error)

	CreateBucketRequest(*storage.CreateBucketInput) (*request.Request, *storage.CreateBucketOutput)

	CreateBucket(*storage.CreateBucketInput) (*storage.CreateBucketOutput, error)

	CreateMultipartUploadRequest(*storage.CreateMultipartUploadInput) (*request.Request, *storage.CreateMultipartUploadOutput)

	CreateMultipartUpload(*storage.CreateMultipartUploadInput) (*storage.CreateMultipartUploadOutput, error)

	DeleteBucketRequest(*storage.DeleteBucketInput) (*request.Request, *storage.DeleteBucketOutput)

	DeleteBucket(*storage.DeleteBucketInput) (*storage.DeleteBucketOutput, error)

	DeleteBucketAnalyticsConfigurationRequest(*storage.DeleteBucketAnalyticsConfigurationInput) (*request.Request, *storage.DeleteBucketAnalyticsConfigurationOutput)

	DeleteBucketAnalyticsConfiguration(*storage.DeleteBucketAnalyticsConfigurationInput) (*storage.DeleteBucketAnalyticsConfigurationOutput, error)

	DeleteBucketCorsRequest(*storage.DeleteBucketCorsInput) (*request.Request, *storage.DeleteBucketCorsOutput)

	DeleteBucketCors(*storage.DeleteBucketCorsInput) (*storage.DeleteBucketCorsOutput, error)

	DeleteBucketInventoryConfigurationRequest(*storage.DeleteBucketInventoryConfigurationInput) (*request.Request, *storage.DeleteBucketInventoryConfigurationOutput)

	DeleteBucketInventoryConfiguration(*storage.DeleteBucketInventoryConfigurationInput) (*storage.DeleteBucketInventoryConfigurationOutput, error)

	DeleteBucketLifecycleRequest(*storage.DeleteBucketLifecycleInput) (*request.Request, *storage.DeleteBucketLifecycleOutput)

	DeleteBucketLifecycle(*storage.DeleteBucketLifecycleInput) (*storage.DeleteBucketLifecycleOutput, error)

	DeleteBucketMetricsConfigurationRequest(*storage.DeleteBucketMetricsConfigurationInput) (*request.Request, *storage.DeleteBucketMetricsConfigurationOutput)

	DeleteBucketMetricsConfiguration(*storage.DeleteBucketMetricsConfigurationInput) (*storage.DeleteBucketMetricsConfigurationOutput, error)

	DeleteBucketPolicyRequest(*storage.DeleteBucketPolicyInput) (*request.Request, *storage.DeleteBucketPolicyOutput)

	DeleteBucketPolicy(*storage.DeleteBucketPolicyInput) (*storage.DeleteBucketPolicyOutput, error)

	DeleteBucketReplicationRequest(*storage.DeleteBucketReplicationInput) (*request.Request, *storage.DeleteBucketReplicationOutput)

	DeleteBucketReplication(*storage.DeleteBucketReplicationInput) (*storage.DeleteBucketReplicationOutput, error)

	DeleteBucketTaggingRequest(*storage.DeleteBucketTaggingInput) (*request.Request, *storage.DeleteBucketTaggingOutput)

	DeleteBucketTagging(*storage.DeleteBucketTaggingInput) (*storage.DeleteBucketTaggingOutput, error)

	DeleteBucketWebsiteRequest(*storage.DeleteBucketWebsiteInput) (*request.Request, *storage.DeleteBucketWebsiteOutput)

	DeleteBucketWebsite(*storage.DeleteBucketWebsiteInput) (*storage.DeleteBucketWebsiteOutput, error)

	DeleteObjectRequest(*storage.DeleteObjectInput) (*request.Request, *storage.DeleteObjectOutput)

	DeleteObject(*storage.DeleteObjectInput) (*storage.DeleteObjectOutput, error)

	DeleteObjectTaggingRequest(*storage.DeleteObjectTaggingInput) (*request.Request, *storage.DeleteObjectTaggingOutput)

	DeleteObjectTagging(*storage.DeleteObjectTaggingInput) (*storage.DeleteObjectTaggingOutput, error)

	DeleteObjectsRequest(*storage.DeleteObjectsInput) (*request.Request, *storage.DeleteObjectsOutput)

	DeleteObjects(*storage.DeleteObjectsInput) (*storage.DeleteObjectsOutput, error)

	GetBucketAccelerateConfigurationRequest(*storage.GetBucketAccelerateConfigurationInput) (*request.Request, *storage.GetBucketAccelerateConfigurationOutput)

	GetBucketAccelerateConfiguration(*storage.GetBucketAccelerateConfigurationInput) (*storage.GetBucketAccelerateConfigurationOutput, error)

	GetBucketAclRequest(*storage.GetBucketAclInput) (*request.Request, *storage.GetBucketAclOutput)

	GetBucketAcl(*storage.GetBucketAclInput) (*storage.GetBucketAclOutput, error)

	GetBucketAnalyticsConfigurationRequest(*storage.GetBucketAnalyticsConfigurationInput) (*request.Request, *storage.GetBucketAnalyticsConfigurationOutput)

	GetBucketAnalyticsConfiguration(*storage.GetBucketAnalyticsConfigurationInput) (*storage.GetBucketAnalyticsConfigurationOutput, error)

	GetBucketCorsRequest(*storage.GetBucketCorsInput) (*request.Request, *storage.GetBucketCorsOutput)

	GetBucketCors(*storage.GetBucketCorsInput) (*storage.GetBucketCorsOutput, error)

	GetBucketInventoryConfigurationRequest(*storage.GetBucketInventoryConfigurationInput) (*request.Request, *storage.GetBucketInventoryConfigurationOutput)

	GetBucketInventoryConfiguration(*storage.GetBucketInventoryConfigurationInput) (*storage.GetBucketInventoryConfigurationOutput, error)

	GetBucketLifecycleRequest(*storage.GetBucketLifecycleInput) (*request.Request, *storage.GetBucketLifecycleOutput)

	GetBucketLifecycle(*storage.GetBucketLifecycleInput) (*storage.GetBucketLifecycleOutput, error)

	GetBucketLifecycleConfigurationRequest(*storage.GetBucketLifecycleConfigurationInput) (*request.Request, *storage.GetBucketLifecycleConfigurationOutput)

	GetBucketLifecycleConfiguration(*storage.GetBucketLifecycleConfigurationInput) (*storage.GetBucketLifecycleConfigurationOutput, error)

	GetBucketLocationRequest(*storage.GetBucketLocationInput) (*request.Request, *storage.GetBucketLocationOutput)

	GetBucketLocation(*storage.GetBucketLocationInput) (*storage.GetBucketLocationOutput, error)

	GetBucketLoggingRequest(*storage.GetBucketLoggingInput) (*request.Request, *storage.GetBucketLoggingOutput)

	GetBucketLogging(*storage.GetBucketLoggingInput) (*storage.GetBucketLoggingOutput, error)

	GetBucketMetricsConfigurationRequest(*storage.GetBucketMetricsConfigurationInput) (*request.Request, *storage.GetBucketMetricsConfigurationOutput)

	GetBucketMetricsConfiguration(*storage.GetBucketMetricsConfigurationInput) (*storage.GetBucketMetricsConfigurationOutput, error)

	GetBucketNotificationRequest(*storage.GetBucketNotificationConfigurationRequest) (*request.Request, *storage.NotificationConfigurationDeprecated)

	GetBucketNotification(*storage.GetBucketNotificationConfigurationRequest) (*storage.NotificationConfigurationDeprecated, error)

	GetBucketNotificationConfigurationRequest(*storage.GetBucketNotificationConfigurationRequest) (*request.Request, *storage.NotificationConfiguration)

	GetBucketNotificationConfiguration(*storage.GetBucketNotificationConfigurationRequest) (*storage.NotificationConfiguration, error)

	GetBucketPolicyRequest(*storage.GetBucketPolicyInput) (*request.Request, *storage.GetBucketPolicyOutput)

	GetBucketPolicy(*storage.GetBucketPolicyInput) (*storage.GetBucketPolicyOutput, error)

	GetBucketReplicationRequest(*storage.GetBucketReplicationInput) (*request.Request, *storage.GetBucketReplicationOutput)

	GetBucketReplication(*storage.GetBucketReplicationInput) (*storage.GetBucketReplicationOutput, error)

	GetBucketRequestPaymentRequest(*storage.GetBucketRequestPaymentInput) (*request.Request, *storage.GetBucketRequestPaymentOutput)

	GetBucketRequestPayment(*storage.GetBucketRequestPaymentInput) (*storage.GetBucketRequestPaymentOutput, error)

	GetBucketTaggingRequest(*storage.GetBucketTaggingInput) (*request.Request, *storage.GetBucketTaggingOutput)

	GetBucketTagging(*storage.GetBucketTaggingInput) (*storage.GetBucketTaggingOutput, error)

	GetBucketVersioningRequest(*storage.GetBucketVersioningInput) (*request.Request, *storage.GetBucketVersioningOutput)

	GetBucketVersioning(*storage.GetBucketVersioningInput) (*storage.GetBucketVersioningOutput, error)

	GetBucketWebsiteRequest(*storage.GetBucketWebsiteInput) (*request.Request, *storage.GetBucketWebsiteOutput)

	GetBucketWebsite(*storage.GetBucketWebsiteInput) (*storage.GetBucketWebsiteOutput, error)

	GetObjectRequest(*storage.GetObjectInput) (*request.Request, *storage.GetObjectOutput)

	GetObject(*storage.GetObjectInput) (*storage.GetObjectOutput, error)

	GetObjectAclRequest(*storage.GetObjectAclInput) (*request.Request, *storage.GetObjectAclOutput)

	GetObjectAcl(*storage.GetObjectAclInput) (*storage.GetObjectAclOutput, error)

	GetObjectTaggingRequest(*storage.GetObjectTaggingInput) (*request.Request, *storage.GetObjectTaggingOutput)

	GetObjectTagging(*storage.GetObjectTaggingInput) (*storage.GetObjectTaggingOutput, error)

	GetObjectTorrentRequest(*storage.GetObjectTorrentInput) (*request.Request, *storage.GetObjectTorrentOutput)

	GetObjectTorrent(*storage.GetObjectTorrentInput) (*storage.GetObjectTorrentOutput, error)

	HeadBucketRequest(*storage.HeadBucketInput) (*request.Request, *storage.HeadBucketOutput)

	HeadBucket(*storage.HeadBucketInput) (*storage.HeadBucketOutput, error)

	HeadObjectRequest(*storage.HeadObjectInput) (*request.Request, *storage.HeadObjectOutput)

	HeadObject(*storage.HeadObjectInput) (*storage.HeadObjectOutput, error)

	ListBucketAnalyticsConfigurationsRequest(*storage.ListBucketAnalyticsConfigurationsInput) (*request.Request, *storage.ListBucketAnalyticsConfigurationsOutput)

	ListBucketAnalyticsConfigurations(*storage.ListBucketAnalyticsConfigurationsInput) (*storage.ListBucketAnalyticsConfigurationsOutput, error)

	ListBucketInventoryConfigurationsRequest(*storage.ListBucketInventoryConfigurationsInput) (*request.Request, *storage.ListBucketInventoryConfigurationsOutput)

	ListBucketInventoryConfigurations(*storage.ListBucketInventoryConfigurationsInput) (*storage.ListBucketInventoryConfigurationsOutput, error)

	ListBucketMetricsConfigurationsRequest(*storage.ListBucketMetricsConfigurationsInput) (*request.Request, *storage.ListBucketMetricsConfigurationsOutput)

	ListBucketMetricsConfigurations(*storage.ListBucketMetricsConfigurationsInput) (*storage.ListBucketMetricsConfigurationsOutput, error)

	ListBucketsRequest(*storage.ListBucketsInput) (*request.Request, *storage.ListBucketsOutput)

	ListBuckets(*storage.ListBucketsInput) (*storage.ListBucketsOutput, error)

	ListMultipartUploadsRequest(*storage.ListMultipartUploadsInput) (*request.Request, *storage.ListMultipartUploadsOutput)

	ListMultipartUploads(*storage.ListMultipartUploadsInput) (*storage.ListMultipartUploadsOutput, error)

	ListMultipartUploadsPages(*storage.ListMultipartUploadsInput, func(*storage.ListMultipartUploadsOutput, bool) bool) error

	ListObjectVersionsRequest(*storage.ListObjectVersionsInput) (*request.Request, *storage.ListObjectVersionsOutput)

	ListObjectVersions(*storage.ListObjectVersionsInput) (*storage.ListObjectVersionsOutput, error)

	ListObjectVersionsPages(*storage.ListObjectVersionsInput, func(*storage.ListObjectVersionsOutput, bool) bool) error

	ListObjectsRequest(*storage.ListObjectsInput) (*request.Request, *storage.ListObjectsOutput)

	ListObjects(*storage.ListObjectsInput) (*storage.ListObjectsOutput, error)

	ListObjectsPages(*storage.ListObjectsInput, func(*storage.ListObjectsOutput, bool) bool) error

	ListObjectsV2Request(*storage.ListObjectsV2Input) (*request.Request, *storage.ListObjectsV2Output)

	ListObjectsV2(*storage.ListObjectsV2Input) (*storage.ListObjectsV2Output, error)

	ListObjectsV2Pages(*storage.ListObjectsV2Input, func(*storage.ListObjectsV2Output, bool) bool) error

	ListPartsRequest(*storage.ListPartsInput) (*request.Request, *storage.ListPartsOutput)

	ListParts(*storage.ListPartsInput) (*storage.ListPartsOutput, error)

	ListPartsPages(*storage.ListPartsInput, func(*storage.ListPartsOutput, bool) bool) error

	PutBucketAccelerateConfigurationRequest(*storage.PutBucketAccelerateConfigurationInput) (*request.Request, *storage.PutBucketAccelerateConfigurationOutput)

	PutBucketAccelerateConfiguration(*storage.PutBucketAccelerateConfigurationInput) (*storage.PutBucketAccelerateConfigurationOutput, error)

	PutBucketAclRequest(*storage.PutBucketAclInput) (*request.Request, *storage.PutBucketAclOutput)

	PutBucketAcl(*storage.PutBucketAclInput) (*storage.PutBucketAclOutput, error)

	PutBucketAnalyticsConfigurationRequest(*storage.PutBucketAnalyticsConfigurationInput) (*request.Request, *storage.PutBucketAnalyticsConfigurationOutput)

	PutBucketAnalyticsConfiguration(*storage.PutBucketAnalyticsConfigurationInput) (*storage.PutBucketAnalyticsConfigurationOutput, error)

	PutBucketCorsRequest(*storage.PutBucketCorsInput) (*request.Request, *storage.PutBucketCorsOutput)

	PutBucketCors(*storage.PutBucketCorsInput) (*storage.PutBucketCorsOutput, error)

	PutBucketInventoryConfigurationRequest(*storage.PutBucketInventoryConfigurationInput) (*request.Request, *storage.PutBucketInventoryConfigurationOutput)

	PutBucketInventoryConfiguration(*storage.PutBucketInventoryConfigurationInput) (*storage.PutBucketInventoryConfigurationOutput, error)

	PutBucketLifecycleRequest(*storage.PutBucketLifecycleInput) (*request.Request, *storage.PutBucketLifecycleOutput)

	PutBucketLifecycle(*storage.PutBucketLifecycleInput) (*storage.PutBucketLifecycleOutput, error)

	PutBucketLifecycleConfigurationRequest(*storage.PutBucketLifecycleConfigurationInput) (*request.Request, *storage.PutBucketLifecycleConfigurationOutput)

	PutBucketLifecycleConfiguration(*storage.PutBucketLifecycleConfigurationInput) (*storage.PutBucketLifecycleConfigurationOutput, error)

	PutBucketLoggingRequest(*storage.PutBucketLoggingInput) (*request.Request, *storage.PutBucketLoggingOutput)

	PutBucketLogging(*storage.PutBucketLoggingInput) (*storage.PutBucketLoggingOutput, error)

	PutBucketMetricsConfigurationRequest(*storage.PutBucketMetricsConfigurationInput) (*request.Request, *storage.PutBucketMetricsConfigurationOutput)

	PutBucketMetricsConfiguration(*storage.PutBucketMetricsConfigurationInput) (*storage.PutBucketMetricsConfigurationOutput, error)

	PutBucketNotificationRequest(*storage.PutBucketNotificationInput) (*request.Request, *storage.PutBucketNotificationOutput)

	PutBucketNotification(*storage.PutBucketNotificationInput) (*storage.PutBucketNotificationOutput, error)

	PutBucketNotificationConfigurationRequest(*storage.PutBucketNotificationConfigurationInput) (*request.Request, *storage.PutBucketNotificationConfigurationOutput)

	PutBucketNotificationConfiguration(*storage.PutBucketNotificationConfigurationInput) (*storage.PutBucketNotificationConfigurationOutput, error)

	PutBucketPolicyRequest(*storage.PutBucketPolicyInput) (*request.Request, *storage.PutBucketPolicyOutput)

	PutBucketPolicy(*storage.PutBucketPolicyInput) (*storage.PutBucketPolicyOutput, error)

	PutBucketReplicationRequest(*storage.PutBucketReplicationInput) (*request.Request, *storage.PutBucketReplicationOutput)

	PutBucketReplication(*storage.PutBucketReplicationInput) (*storage.PutBucketReplicationOutput, error)

	PutBucketRequestPaymentRequest(*storage.PutBucketRequestPaymentInput) (*request.Request, *storage.PutBucketRequestPaymentOutput)

	PutBucketRequestPayment(*storage.PutBucketRequestPaymentInput) (*storage.PutBucketRequestPaymentOutput, error)

	PutBucketTaggingRequest(*storage.PutBucketTaggingInput) (*request.Request, *storage.PutBucketTaggingOutput)

	PutBucketTagging(*storage.PutBucketTaggingInput) (*storage.PutBucketTaggingOutput, error)

	PutBucketVersioningRequest(*storage.PutBucketVersioningInput) (*request.Request, *storage.PutBucketVersioningOutput)

	PutBucketVersioning(*storage.PutBucketVersioningInput) (*storage.PutBucketVersioningOutput, error)

	PutBucketWebsiteRequest(*storage.PutBucketWebsiteInput) (*request.Request, *storage.PutBucketWebsiteOutput)

	PutBucketWebsite(*storage.PutBucketWebsiteInput) (*storage.PutBucketWebsiteOutput, error)

	PutObjectRequest(*storage.PutObjectInput) (*request.Request, *storage.PutObjectOutput)

	PutObject(*storage.PutObjectInput) (*storage.PutObjectOutput, error)

	PutObjectAclRequest(*storage.PutObjectAclInput) (*request.Request, *storage.PutObjectAclOutput)

	PutObjectAcl(*storage.PutObjectAclInput) (*storage.PutObjectAclOutput, error)

	PutObjectTaggingRequest(*storage.PutObjectTaggingInput) (*request.Request, *storage.PutObjectTaggingOutput)

	PutObjectTagging(*storage.PutObjectTaggingInput) (*storage.PutObjectTaggingOutput, error)

	RestoreObjectRequest(*storage.RestoreObjectInput) (*request.Request, *storage.RestoreObjectOutput)

	RestoreObject(*storage.RestoreObjectInput) (*storage.RestoreObjectOutput, error)

	UploadPartRequest(*storage.UploadPartInput) (*request.Request, *storage.UploadPartOutput)

	UploadPart(*storage.UploadPartInput) (*storage.UploadPartOutput, error)

	UploadPartCopyRequest(*storage.UploadPartCopyInput) (*request.Request, *storage.UploadPartCopyOutput)

	UploadPartCopy(*storage.UploadPartCopyInput) (*storage.UploadPartCopyOutput, error)

	WaitUntilBucketExists(*storage.HeadBucketInput) error

	WaitUntilBucketNotExists(*storage.HeadBucketInput) error

	WaitUntilObjectExists(*storage.HeadObjectInput) error

	WaitUntilObjectNotExists(*storage.HeadObjectInput) error
}

var _ storageAPI = (*storage.storage)(nil)
