// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package objectstorageiface provides an interface to enable mocking the NIFTYCloud ObjectStorage service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package objectstorageiface

import (
	"github.com/tily/sdk-go/aws/request"
	"github.com/tily/sdk-go/service/objectstorage"
)

// objectstorageAPI provides an interface to enable mocking the
// objectstorage.objectstorage service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // NIFTYCloud ObjectStorage.
//    func myFunc(svc objectstorageiface.objectstorageAPI) bool {
//        // Make svc.AbortMultipartUpload request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := objectstorage.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockobjectstorageClient struct {
//        objectstorageiface.objectstorageAPI
//    }
//    func (m *mockobjectstorageClient) AbortMultipartUpload(input *objectstorage.AbortMultipartUploadInput) (*objectstorage.AbortMultipartUploadOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockobjectstorageClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type objectstorageAPI interface {
	AbortMultipartUploadRequest(*objectstorage.AbortMultipartUploadInput) (*request.Request, *objectstorage.AbortMultipartUploadOutput)

	AbortMultipartUpload(*objectstorage.AbortMultipartUploadInput) (*objectstorage.AbortMultipartUploadOutput, error)

	CompleteMultipartUploadRequest(*objectstorage.CompleteMultipartUploadInput) (*request.Request, *objectstorage.CompleteMultipartUploadOutput)

	CompleteMultipartUpload(*objectstorage.CompleteMultipartUploadInput) (*objectstorage.CompleteMultipartUploadOutput, error)

	CopyObjectRequest(*objectstorage.CopyObjectInput) (*request.Request, *objectstorage.CopyObjectOutput)

	CopyObject(*objectstorage.CopyObjectInput) (*objectstorage.CopyObjectOutput, error)

	CreateBucketRequest(*objectstorage.CreateBucketInput) (*request.Request, *objectstorage.CreateBucketOutput)

	CreateBucket(*objectstorage.CreateBucketInput) (*objectstorage.CreateBucketOutput, error)

	CreateMultipartUploadRequest(*objectstorage.CreateMultipartUploadInput) (*request.Request, *objectstorage.CreateMultipartUploadOutput)

	CreateMultipartUpload(*objectstorage.CreateMultipartUploadInput) (*objectstorage.CreateMultipartUploadOutput, error)

	DeleteBucketRequest(*objectstorage.DeleteBucketInput) (*request.Request, *objectstorage.DeleteBucketOutput)

	DeleteBucket(*objectstorage.DeleteBucketInput) (*objectstorage.DeleteBucketOutput, error)

	DeleteBucketAnalyticsConfigurationRequest(*objectstorage.DeleteBucketAnalyticsConfigurationInput) (*request.Request, *objectstorage.DeleteBucketAnalyticsConfigurationOutput)

	DeleteBucketAnalyticsConfiguration(*objectstorage.DeleteBucketAnalyticsConfigurationInput) (*objectstorage.DeleteBucketAnalyticsConfigurationOutput, error)

	DeleteBucketCorsRequest(*objectstorage.DeleteBucketCorsInput) (*request.Request, *objectstorage.DeleteBucketCorsOutput)

	DeleteBucketCors(*objectstorage.DeleteBucketCorsInput) (*objectstorage.DeleteBucketCorsOutput, error)

	DeleteBucketInventoryConfigurationRequest(*objectstorage.DeleteBucketInventoryConfigurationInput) (*request.Request, *objectstorage.DeleteBucketInventoryConfigurationOutput)

	DeleteBucketInventoryConfiguration(*objectstorage.DeleteBucketInventoryConfigurationInput) (*objectstorage.DeleteBucketInventoryConfigurationOutput, error)

	DeleteBucketLifecycleRequest(*objectstorage.DeleteBucketLifecycleInput) (*request.Request, *objectstorage.DeleteBucketLifecycleOutput)

	DeleteBucketLifecycle(*objectstorage.DeleteBucketLifecycleInput) (*objectstorage.DeleteBucketLifecycleOutput, error)

	DeleteBucketMetricsConfigurationRequest(*objectstorage.DeleteBucketMetricsConfigurationInput) (*request.Request, *objectstorage.DeleteBucketMetricsConfigurationOutput)

	DeleteBucketMetricsConfiguration(*objectstorage.DeleteBucketMetricsConfigurationInput) (*objectstorage.DeleteBucketMetricsConfigurationOutput, error)

	DeleteBucketPolicyRequest(*objectstorage.DeleteBucketPolicyInput) (*request.Request, *objectstorage.DeleteBucketPolicyOutput)

	DeleteBucketPolicy(*objectstorage.DeleteBucketPolicyInput) (*objectstorage.DeleteBucketPolicyOutput, error)

	DeleteBucketReplicationRequest(*objectstorage.DeleteBucketReplicationInput) (*request.Request, *objectstorage.DeleteBucketReplicationOutput)

	DeleteBucketReplication(*objectstorage.DeleteBucketReplicationInput) (*objectstorage.DeleteBucketReplicationOutput, error)

	DeleteBucketTaggingRequest(*objectstorage.DeleteBucketTaggingInput) (*request.Request, *objectstorage.DeleteBucketTaggingOutput)

	DeleteBucketTagging(*objectstorage.DeleteBucketTaggingInput) (*objectstorage.DeleteBucketTaggingOutput, error)

	DeleteBucketWebsiteRequest(*objectstorage.DeleteBucketWebsiteInput) (*request.Request, *objectstorage.DeleteBucketWebsiteOutput)

	DeleteBucketWebsite(*objectstorage.DeleteBucketWebsiteInput) (*objectstorage.DeleteBucketWebsiteOutput, error)

	DeleteObjectRequest(*objectstorage.DeleteObjectInput) (*request.Request, *objectstorage.DeleteObjectOutput)

	DeleteObject(*objectstorage.DeleteObjectInput) (*objectstorage.DeleteObjectOutput, error)

	DeleteObjectTaggingRequest(*objectstorage.DeleteObjectTaggingInput) (*request.Request, *objectstorage.DeleteObjectTaggingOutput)

	DeleteObjectTagging(*objectstorage.DeleteObjectTaggingInput) (*objectstorage.DeleteObjectTaggingOutput, error)

	DeleteObjectsRequest(*objectstorage.DeleteObjectsInput) (*request.Request, *objectstorage.DeleteObjectsOutput)

	DeleteObjects(*objectstorage.DeleteObjectsInput) (*objectstorage.DeleteObjectsOutput, error)

	GetBucketAccelerateConfigurationRequest(*objectstorage.GetBucketAccelerateConfigurationInput) (*request.Request, *objectstorage.GetBucketAccelerateConfigurationOutput)

	GetBucketAccelerateConfiguration(*objectstorage.GetBucketAccelerateConfigurationInput) (*objectstorage.GetBucketAccelerateConfigurationOutput, error)

	GetBucketAclRequest(*objectstorage.GetBucketAclInput) (*request.Request, *objectstorage.GetBucketAclOutput)

	GetBucketAcl(*objectstorage.GetBucketAclInput) (*objectstorage.GetBucketAclOutput, error)

	GetBucketAnalyticsConfigurationRequest(*objectstorage.GetBucketAnalyticsConfigurationInput) (*request.Request, *objectstorage.GetBucketAnalyticsConfigurationOutput)

	GetBucketAnalyticsConfiguration(*objectstorage.GetBucketAnalyticsConfigurationInput) (*objectstorage.GetBucketAnalyticsConfigurationOutput, error)

	GetBucketCorsRequest(*objectstorage.GetBucketCorsInput) (*request.Request, *objectstorage.GetBucketCorsOutput)

	GetBucketCors(*objectstorage.GetBucketCorsInput) (*objectstorage.GetBucketCorsOutput, error)

	GetBucketInventoryConfigurationRequest(*objectstorage.GetBucketInventoryConfigurationInput) (*request.Request, *objectstorage.GetBucketInventoryConfigurationOutput)

	GetBucketInventoryConfiguration(*objectstorage.GetBucketInventoryConfigurationInput) (*objectstorage.GetBucketInventoryConfigurationOutput, error)

	GetBucketLifecycleRequest(*objectstorage.GetBucketLifecycleInput) (*request.Request, *objectstorage.GetBucketLifecycleOutput)

	GetBucketLifecycle(*objectstorage.GetBucketLifecycleInput) (*objectstorage.GetBucketLifecycleOutput, error)

	GetBucketLifecycleConfigurationRequest(*objectstorage.GetBucketLifecycleConfigurationInput) (*request.Request, *objectstorage.GetBucketLifecycleConfigurationOutput)

	GetBucketLifecycleConfiguration(*objectstorage.GetBucketLifecycleConfigurationInput) (*objectstorage.GetBucketLifecycleConfigurationOutput, error)

	GetBucketLocationRequest(*objectstorage.GetBucketLocationInput) (*request.Request, *objectstorage.GetBucketLocationOutput)

	GetBucketLocation(*objectstorage.GetBucketLocationInput) (*objectstorage.GetBucketLocationOutput, error)

	GetBucketLoggingRequest(*objectstorage.GetBucketLoggingInput) (*request.Request, *objectstorage.GetBucketLoggingOutput)

	GetBucketLogging(*objectstorage.GetBucketLoggingInput) (*objectstorage.GetBucketLoggingOutput, error)

	GetBucketMetricsConfigurationRequest(*objectstorage.GetBucketMetricsConfigurationInput) (*request.Request, *objectstorage.GetBucketMetricsConfigurationOutput)

	GetBucketMetricsConfiguration(*objectstorage.GetBucketMetricsConfigurationInput) (*objectstorage.GetBucketMetricsConfigurationOutput, error)

	GetBucketNotificationRequest(*objectstorage.GetBucketNotificationConfigurationRequest) (*request.Request, *objectstorage.NotificationConfigurationDeprecated)

	GetBucketNotification(*objectstorage.GetBucketNotificationConfigurationRequest) (*objectstorage.NotificationConfigurationDeprecated, error)

	GetBucketNotificationConfigurationRequest(*objectstorage.GetBucketNotificationConfigurationRequest) (*request.Request, *objectstorage.NotificationConfiguration)

	GetBucketNotificationConfiguration(*objectstorage.GetBucketNotificationConfigurationRequest) (*objectstorage.NotificationConfiguration, error)

	GetBucketPolicyRequest(*objectstorage.GetBucketPolicyInput) (*request.Request, *objectstorage.GetBucketPolicyOutput)

	GetBucketPolicy(*objectstorage.GetBucketPolicyInput) (*objectstorage.GetBucketPolicyOutput, error)

	GetBucketReplicationRequest(*objectstorage.GetBucketReplicationInput) (*request.Request, *objectstorage.GetBucketReplicationOutput)

	GetBucketReplication(*objectstorage.GetBucketReplicationInput) (*objectstorage.GetBucketReplicationOutput, error)

	GetBucketRequestPaymentRequest(*objectstorage.GetBucketRequestPaymentInput) (*request.Request, *objectstorage.GetBucketRequestPaymentOutput)

	GetBucketRequestPayment(*objectstorage.GetBucketRequestPaymentInput) (*objectstorage.GetBucketRequestPaymentOutput, error)

	GetBucketTaggingRequest(*objectstorage.GetBucketTaggingInput) (*request.Request, *objectstorage.GetBucketTaggingOutput)

	GetBucketTagging(*objectstorage.GetBucketTaggingInput) (*objectstorage.GetBucketTaggingOutput, error)

	GetBucketVersioningRequest(*objectstorage.GetBucketVersioningInput) (*request.Request, *objectstorage.GetBucketVersioningOutput)

	GetBucketVersioning(*objectstorage.GetBucketVersioningInput) (*objectstorage.GetBucketVersioningOutput, error)

	GetBucketWebsiteRequest(*objectstorage.GetBucketWebsiteInput) (*request.Request, *objectstorage.GetBucketWebsiteOutput)

	GetBucketWebsite(*objectstorage.GetBucketWebsiteInput) (*objectstorage.GetBucketWebsiteOutput, error)

	GetObjectRequest(*objectstorage.GetObjectInput) (*request.Request, *objectstorage.GetObjectOutput)

	GetObject(*objectstorage.GetObjectInput) (*objectstorage.GetObjectOutput, error)

	GetObjectAclRequest(*objectstorage.GetObjectAclInput) (*request.Request, *objectstorage.GetObjectAclOutput)

	GetObjectAcl(*objectstorage.GetObjectAclInput) (*objectstorage.GetObjectAclOutput, error)

	GetObjectTaggingRequest(*objectstorage.GetObjectTaggingInput) (*request.Request, *objectstorage.GetObjectTaggingOutput)

	GetObjectTagging(*objectstorage.GetObjectTaggingInput) (*objectstorage.GetObjectTaggingOutput, error)

	GetObjectTorrentRequest(*objectstorage.GetObjectTorrentInput) (*request.Request, *objectstorage.GetObjectTorrentOutput)

	GetObjectTorrent(*objectstorage.GetObjectTorrentInput) (*objectstorage.GetObjectTorrentOutput, error)

	HeadBucketRequest(*objectstorage.HeadBucketInput) (*request.Request, *objectstorage.HeadBucketOutput)

	HeadBucket(*objectstorage.HeadBucketInput) (*objectstorage.HeadBucketOutput, error)

	HeadObjectRequest(*objectstorage.HeadObjectInput) (*request.Request, *objectstorage.HeadObjectOutput)

	HeadObject(*objectstorage.HeadObjectInput) (*objectstorage.HeadObjectOutput, error)

	ListBucketAnalyticsConfigurationsRequest(*objectstorage.ListBucketAnalyticsConfigurationsInput) (*request.Request, *objectstorage.ListBucketAnalyticsConfigurationsOutput)

	ListBucketAnalyticsConfigurations(*objectstorage.ListBucketAnalyticsConfigurationsInput) (*objectstorage.ListBucketAnalyticsConfigurationsOutput, error)

	ListBucketInventoryConfigurationsRequest(*objectstorage.ListBucketInventoryConfigurationsInput) (*request.Request, *objectstorage.ListBucketInventoryConfigurationsOutput)

	ListBucketInventoryConfigurations(*objectstorage.ListBucketInventoryConfigurationsInput) (*objectstorage.ListBucketInventoryConfigurationsOutput, error)

	ListBucketMetricsConfigurationsRequest(*objectstorage.ListBucketMetricsConfigurationsInput) (*request.Request, *objectstorage.ListBucketMetricsConfigurationsOutput)

	ListBucketMetricsConfigurations(*objectstorage.ListBucketMetricsConfigurationsInput) (*objectstorage.ListBucketMetricsConfigurationsOutput, error)

	ListBucketsRequest(*objectstorage.ListBucketsInput) (*request.Request, *objectstorage.ListBucketsOutput)

	ListBuckets(*objectstorage.ListBucketsInput) (*objectstorage.ListBucketsOutput, error)

	ListMultipartUploadsRequest(*objectstorage.ListMultipartUploadsInput) (*request.Request, *objectstorage.ListMultipartUploadsOutput)

	ListMultipartUploads(*objectstorage.ListMultipartUploadsInput) (*objectstorage.ListMultipartUploadsOutput, error)

	ListMultipartUploadsPages(*objectstorage.ListMultipartUploadsInput, func(*objectstorage.ListMultipartUploadsOutput, bool) bool) error

	ListObjectVersionsRequest(*objectstorage.ListObjectVersionsInput) (*request.Request, *objectstorage.ListObjectVersionsOutput)

	ListObjectVersions(*objectstorage.ListObjectVersionsInput) (*objectstorage.ListObjectVersionsOutput, error)

	ListObjectVersionsPages(*objectstorage.ListObjectVersionsInput, func(*objectstorage.ListObjectVersionsOutput, bool) bool) error

	ListObjectsRequest(*objectstorage.ListObjectsInput) (*request.Request, *objectstorage.ListObjectsOutput)

	ListObjects(*objectstorage.ListObjectsInput) (*objectstorage.ListObjectsOutput, error)

	ListObjectsPages(*objectstorage.ListObjectsInput, func(*objectstorage.ListObjectsOutput, bool) bool) error

	ListObjectsV2Request(*objectstorage.ListObjectsV2Input) (*request.Request, *objectstorage.ListObjectsV2Output)

	ListObjectsV2(*objectstorage.ListObjectsV2Input) (*objectstorage.ListObjectsV2Output, error)

	ListObjectsV2Pages(*objectstorage.ListObjectsV2Input, func(*objectstorage.ListObjectsV2Output, bool) bool) error

	ListPartsRequest(*objectstorage.ListPartsInput) (*request.Request, *objectstorage.ListPartsOutput)

	ListParts(*objectstorage.ListPartsInput) (*objectstorage.ListPartsOutput, error)

	ListPartsPages(*objectstorage.ListPartsInput, func(*objectstorage.ListPartsOutput, bool) bool) error

	PutBucketAccelerateConfigurationRequest(*objectstorage.PutBucketAccelerateConfigurationInput) (*request.Request, *objectstorage.PutBucketAccelerateConfigurationOutput)

	PutBucketAccelerateConfiguration(*objectstorage.PutBucketAccelerateConfigurationInput) (*objectstorage.PutBucketAccelerateConfigurationOutput, error)

	PutBucketAclRequest(*objectstorage.PutBucketAclInput) (*request.Request, *objectstorage.PutBucketAclOutput)

	PutBucketAcl(*objectstorage.PutBucketAclInput) (*objectstorage.PutBucketAclOutput, error)

	PutBucketAnalyticsConfigurationRequest(*objectstorage.PutBucketAnalyticsConfigurationInput) (*request.Request, *objectstorage.PutBucketAnalyticsConfigurationOutput)

	PutBucketAnalyticsConfiguration(*objectstorage.PutBucketAnalyticsConfigurationInput) (*objectstorage.PutBucketAnalyticsConfigurationOutput, error)

	PutBucketCorsRequest(*objectstorage.PutBucketCorsInput) (*request.Request, *objectstorage.PutBucketCorsOutput)

	PutBucketCors(*objectstorage.PutBucketCorsInput) (*objectstorage.PutBucketCorsOutput, error)

	PutBucketInventoryConfigurationRequest(*objectstorage.PutBucketInventoryConfigurationInput) (*request.Request, *objectstorage.PutBucketInventoryConfigurationOutput)

	PutBucketInventoryConfiguration(*objectstorage.PutBucketInventoryConfigurationInput) (*objectstorage.PutBucketInventoryConfigurationOutput, error)

	PutBucketLifecycleRequest(*objectstorage.PutBucketLifecycleInput) (*request.Request, *objectstorage.PutBucketLifecycleOutput)

	PutBucketLifecycle(*objectstorage.PutBucketLifecycleInput) (*objectstorage.PutBucketLifecycleOutput, error)

	PutBucketLifecycleConfigurationRequest(*objectstorage.PutBucketLifecycleConfigurationInput) (*request.Request, *objectstorage.PutBucketLifecycleConfigurationOutput)

	PutBucketLifecycleConfiguration(*objectstorage.PutBucketLifecycleConfigurationInput) (*objectstorage.PutBucketLifecycleConfigurationOutput, error)

	PutBucketLoggingRequest(*objectstorage.PutBucketLoggingInput) (*request.Request, *objectstorage.PutBucketLoggingOutput)

	PutBucketLogging(*objectstorage.PutBucketLoggingInput) (*objectstorage.PutBucketLoggingOutput, error)

	PutBucketMetricsConfigurationRequest(*objectstorage.PutBucketMetricsConfigurationInput) (*request.Request, *objectstorage.PutBucketMetricsConfigurationOutput)

	PutBucketMetricsConfiguration(*objectstorage.PutBucketMetricsConfigurationInput) (*objectstorage.PutBucketMetricsConfigurationOutput, error)

	PutBucketNotificationRequest(*objectstorage.PutBucketNotificationInput) (*request.Request, *objectstorage.PutBucketNotificationOutput)

	PutBucketNotification(*objectstorage.PutBucketNotificationInput) (*objectstorage.PutBucketNotificationOutput, error)

	PutBucketNotificationConfigurationRequest(*objectstorage.PutBucketNotificationConfigurationInput) (*request.Request, *objectstorage.PutBucketNotificationConfigurationOutput)

	PutBucketNotificationConfiguration(*objectstorage.PutBucketNotificationConfigurationInput) (*objectstorage.PutBucketNotificationConfigurationOutput, error)

	PutBucketPolicyRequest(*objectstorage.PutBucketPolicyInput) (*request.Request, *objectstorage.PutBucketPolicyOutput)

	PutBucketPolicy(*objectstorage.PutBucketPolicyInput) (*objectstorage.PutBucketPolicyOutput, error)

	PutBucketReplicationRequest(*objectstorage.PutBucketReplicationInput) (*request.Request, *objectstorage.PutBucketReplicationOutput)

	PutBucketReplication(*objectstorage.PutBucketReplicationInput) (*objectstorage.PutBucketReplicationOutput, error)

	PutBucketRequestPaymentRequest(*objectstorage.PutBucketRequestPaymentInput) (*request.Request, *objectstorage.PutBucketRequestPaymentOutput)

	PutBucketRequestPayment(*objectstorage.PutBucketRequestPaymentInput) (*objectstorage.PutBucketRequestPaymentOutput, error)

	PutBucketTaggingRequest(*objectstorage.PutBucketTaggingInput) (*request.Request, *objectstorage.PutBucketTaggingOutput)

	PutBucketTagging(*objectstorage.PutBucketTaggingInput) (*objectstorage.PutBucketTaggingOutput, error)

	PutBucketVersioningRequest(*objectstorage.PutBucketVersioningInput) (*request.Request, *objectstorage.PutBucketVersioningOutput)

	PutBucketVersioning(*objectstorage.PutBucketVersioningInput) (*objectstorage.PutBucketVersioningOutput, error)

	PutBucketWebsiteRequest(*objectstorage.PutBucketWebsiteInput) (*request.Request, *objectstorage.PutBucketWebsiteOutput)

	PutBucketWebsite(*objectstorage.PutBucketWebsiteInput) (*objectstorage.PutBucketWebsiteOutput, error)

	PutObjectRequest(*objectstorage.PutObjectInput) (*request.Request, *objectstorage.PutObjectOutput)

	PutObject(*objectstorage.PutObjectInput) (*objectstorage.PutObjectOutput, error)

	PutObjectAclRequest(*objectstorage.PutObjectAclInput) (*request.Request, *objectstorage.PutObjectAclOutput)

	PutObjectAcl(*objectstorage.PutObjectAclInput) (*objectstorage.PutObjectAclOutput, error)

	PutObjectTaggingRequest(*objectstorage.PutObjectTaggingInput) (*request.Request, *objectstorage.PutObjectTaggingOutput)

	PutObjectTagging(*objectstorage.PutObjectTaggingInput) (*objectstorage.PutObjectTaggingOutput, error)

	RestoreObjectRequest(*objectstorage.RestoreObjectInput) (*request.Request, *objectstorage.RestoreObjectOutput)

	RestoreObject(*objectstorage.RestoreObjectInput) (*objectstorage.RestoreObjectOutput, error)

	UploadPartRequest(*objectstorage.UploadPartInput) (*request.Request, *objectstorage.UploadPartOutput)

	UploadPart(*objectstorage.UploadPartInput) (*objectstorage.UploadPartOutput, error)

	UploadPartCopyRequest(*objectstorage.UploadPartCopyInput) (*request.Request, *objectstorage.UploadPartCopyOutput)

	UploadPartCopy(*objectstorage.UploadPartCopyInput) (*objectstorage.UploadPartCopyOutput, error)

	WaitUntilBucketExists(*objectstorage.HeadBucketInput) error

	WaitUntilBucketNotExists(*objectstorage.HeadBucketInput) error

	WaitUntilObjectExists(*objectstorage.HeadObjectInput) error

	WaitUntilObjectNotExists(*objectstorage.HeadObjectInput) error
}

var _ objectstorageAPI = (*objectstorage.objectstorage)(nil)
