// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package computingiface provides an interface to enable mocking the computing service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package computingiface

import (
	"github.com/tily/sdk-go/aws/request"
	"github.com/tily/sdk-go/service/computing"
)

// computingAPI provides an interface to enable mocking the
// computing.computing service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // computing.
//    func myFunc(svc computingiface.computingAPI) bool {
//        // Make svc.AllocateAddress request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := computing.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockcomputingClient struct {
//        computingiface.computingAPI
//    }
//    func (m *mockcomputingClient) AllocateAddress(input *computing.AllocateAddressInput) (*computing.AllocateAddressOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockcomputingClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type computingAPI interface {
	AllocateAddressRequest(*computing.AllocateAddressInput) (*request.Request, *computing.AllocateAddressOutput)

	AllocateAddress(*computing.AllocateAddressInput) (*computing.AllocateAddressOutput, error)

	AssociateAddressRequest(*computing.AssociateAddressInput) (*request.Request, *computing.AssociateAddressOutput)

	AssociateAddress(*computing.AssociateAddressInput) (*computing.AssociateAddressOutput, error)

	AssociateRouteTableRequest(*computing.AssociateRouteTableInput) (*request.Request, *computing.AssociateRouteTableOutput)

	AssociateRouteTable(*computing.AssociateRouteTableInput) (*computing.AssociateRouteTableOutput, error)

	AssociateUsersRequest(*computing.AssociateUsersInput) (*request.Request, *computing.AssociateUsersOutput)

	AssociateUsers(*computing.AssociateUsersInput) (*computing.AssociateUsersOutput, error)

	AttachVolumeRequest(*computing.AttachVolumeInput) (*request.Request, *computing.AttachVolumeOutput)

	AttachVolume(*computing.AttachVolumeInput) (*computing.AttachVolumeOutput, error)

	AuthorizeSecurityGroupIngressRequest(*computing.AuthorizeSecurityGroupIngressInput) (*request.Request, *computing.AuthorizeSecurityGroupIngressOutput)

	AuthorizeSecurityGroupIngress(*computing.AuthorizeSecurityGroupIngressInput) (*computing.AuthorizeSecurityGroupIngressOutput, error)

	CancelCopyInstancesRequest(*computing.CancelCopyInstancesInput) (*request.Request, *computing.CancelCopyInstancesOutput)

	CancelCopyInstances(*computing.CancelCopyInstancesInput) (*computing.CancelCopyInstancesOutput, error)

	CancelUploadRequest(*computing.CancelUploadInput) (*request.Request, *computing.CancelUploadOutput)

	CancelUpload(*computing.CancelUploadInput) (*computing.CancelUploadOutput, error)

	ClearLoadBalancerSessionRequest(*computing.ClearLoadBalancerSessionInput) (*request.Request, *computing.ClearLoadBalancerSessionOutput)

	ClearLoadBalancerSession(*computing.ClearLoadBalancerSessionInput) (*computing.ClearLoadBalancerSessionOutput, error)

	ConfigureHealthCheckRequest(*computing.ConfigureHealthCheckInput) (*request.Request, *computing.ConfigureHealthCheckOutput)

	ConfigureHealthCheck(*computing.ConfigureHealthCheckInput) (*computing.ConfigureHealthCheckOutput, error)

	CopyInstancesRequest(*computing.CopyInstancesInput) (*request.Request, *computing.CopyInstancesOutput)

	CopyInstances(*computing.CopyInstancesInput) (*computing.CopyInstancesOutput, error)

	CreateCustomerGatewayRequest(*computing.CreateCustomerGatewayInput) (*request.Request, *computing.CreateCustomerGatewayOutput)

	CreateCustomerGateway(*computing.CreateCustomerGatewayInput) (*computing.CreateCustomerGatewayOutput, error)

	CreateDhcpOptionsRequest(*computing.CreateDhcpOptionsInput) (*request.Request, *computing.CreateDhcpOptionsOutput)

	CreateDhcpOptions(*computing.CreateDhcpOptionsInput) (*computing.CreateDhcpOptionsOutput, error)

	CreateImageRequest(*computing.CreateImageInput) (*request.Request, *computing.CreateImageOutput)

	CreateImage(*computing.CreateImageInput) (*computing.CreateImageOutput, error)

	CreateKeyPairRequest(*computing.CreateKeyPairInput) (*request.Request, *computing.CreateKeyPairOutput)

	CreateKeyPair(*computing.CreateKeyPairInput) (*computing.CreateKeyPairOutput, error)

	CreateLoadBalancerRequest(*computing.CreateLoadBalancerInput) (*request.Request, *computing.CreateLoadBalancerOutput)

	CreateLoadBalancer(*computing.CreateLoadBalancerInput) (*computing.CreateLoadBalancerOutput, error)

	CreateRouteRequest(*computing.CreateRouteInput) (*request.Request, *computing.CreateRouteOutput)

	CreateRoute(*computing.CreateRouteInput) (*computing.CreateRouteOutput, error)

	CreateRouteTableRequest(*computing.CreateRouteTableInput) (*request.Request, *computing.CreateRouteTableOutput)

	CreateRouteTable(*computing.CreateRouteTableInput) (*computing.CreateRouteTableOutput, error)

	CreateSecurityGroupRequest(*computing.CreateSecurityGroupInput) (*request.Request, *computing.CreateSecurityGroupOutput)

	CreateSecurityGroup(*computing.CreateSecurityGroupInput) (*computing.CreateSecurityGroupOutput, error)

	CreateSslCertificateRequest(*computing.CreateSslCertificateInput) (*request.Request, *computing.CreateSslCertificateOutput)

	CreateSslCertificate(*computing.CreateSslCertificateInput) (*computing.CreateSslCertificateOutput, error)

	CreateVolumeRequest(*computing.CreateVolumeInput) (*request.Request, *computing.CreateVolumeOutput)

	CreateVolume(*computing.CreateVolumeInput) (*computing.CreateVolumeOutput, error)

	CreateVpnConnectionRequest(*computing.CreateVpnConnectionInput) (*request.Request, *computing.CreateVpnConnectionOutput)

	CreateVpnConnection(*computing.CreateVpnConnectionInput) (*computing.CreateVpnConnectionOutput, error)

	CreateVpnGatewayRequest(*computing.CreateVpnGatewayInput) (*request.Request, *computing.CreateVpnGatewayOutput)

	CreateVpnGateway(*computing.CreateVpnGatewayInput) (*computing.CreateVpnGatewayOutput, error)

	DeleteCustomerGatewayRequest(*computing.DeleteCustomerGatewayInput) (*request.Request, *computing.DeleteCustomerGatewayOutput)

	DeleteCustomerGateway(*computing.DeleteCustomerGatewayInput) (*computing.DeleteCustomerGatewayOutput, error)

	DeleteDhcpOptionsRequest(*computing.DeleteDhcpOptionsInput) (*request.Request, *computing.DeleteDhcpOptionsOutput)

	DeleteDhcpOptions(*computing.DeleteDhcpOptionsInput) (*computing.DeleteDhcpOptionsOutput, error)

	DeleteImageRequest(*computing.DeleteImageInput) (*request.Request, *computing.DeleteImageOutput)

	DeleteImage(*computing.DeleteImageInput) (*computing.DeleteImageOutput, error)

	DeleteKeyPairRequest(*computing.DeleteKeyPairInput) (*request.Request, *computing.DeleteKeyPairOutput)

	DeleteKeyPair(*computing.DeleteKeyPairInput) (*computing.DeleteKeyPairOutput, error)

	DeleteLoadBalancerRequest(*computing.DeleteLoadBalancerInput) (*request.Request, *computing.DeleteLoadBalancerOutput)

	DeleteLoadBalancer(*computing.DeleteLoadBalancerInput) (*computing.DeleteLoadBalancerOutput, error)

	DeleteRouteRequest(*computing.DeleteRouteInput) (*request.Request, *computing.DeleteRouteOutput)

	DeleteRoute(*computing.DeleteRouteInput) (*computing.DeleteRouteOutput, error)

	DeleteRouteTableRequest(*computing.DeleteRouteTableInput) (*request.Request, *computing.DeleteRouteTableOutput)

	DeleteRouteTable(*computing.DeleteRouteTableInput) (*computing.DeleteRouteTableOutput, error)

	DeleteSecurityGroupRequest(*computing.DeleteSecurityGroupInput) (*request.Request, *computing.DeleteSecurityGroupOutput)

	DeleteSecurityGroup(*computing.DeleteSecurityGroupInput) (*computing.DeleteSecurityGroupOutput, error)

	DeleteSslCertificateRequest(*computing.DeleteSslCertificateInput) (*request.Request, *computing.DeleteSslCertificateOutput)

	DeleteSslCertificate(*computing.DeleteSslCertificateInput) (*computing.DeleteSslCertificateOutput, error)

	DeleteVolumeRequest(*computing.DeleteVolumeInput) (*request.Request, *computing.DeleteVolumeOutput)

	DeleteVolume(*computing.DeleteVolumeInput) (*computing.DeleteVolumeOutput, error)

	DeleteVpnConnectionRequest(*computing.DeleteVpnConnectionInput) (*request.Request, *computing.DeleteVpnConnectionOutput)

	DeleteVpnConnection(*computing.DeleteVpnConnectionInput) (*computing.DeleteVpnConnectionOutput, error)

	DeleteVpnGatewayRequest(*computing.DeleteVpnGatewayInput) (*request.Request, *computing.DeleteVpnGatewayOutput)

	DeleteVpnGateway(*computing.DeleteVpnGatewayInput) (*computing.DeleteVpnGatewayOutput, error)

	DeregisterInstancesFromLoadBalancerRequest(*computing.DeregisterInstancesFromLoadBalancerInput) (*request.Request, *computing.DeregisterInstancesFromLoadBalancerOutput)

	DeregisterInstancesFromLoadBalancer(*computing.DeregisterInstancesFromLoadBalancerInput) (*computing.DeregisterInstancesFromLoadBalancerOutput, error)

	DeregisterInstancesFromSecurityGroupRequest(*computing.DeregisterInstancesFromSecurityGroupInput) (*request.Request, *computing.DeregisterInstancesFromSecurityGroupOutput)

	DeregisterInstancesFromSecurityGroup(*computing.DeregisterInstancesFromSecurityGroupInput) (*computing.DeregisterInstancesFromSecurityGroupOutput, error)

	DescribeAddressesRequest(*computing.DescribeAddressesInput) (*request.Request, *computing.DescribeAddressesOutput)

	DescribeAddresses(*computing.DescribeAddressesInput) (*computing.DescribeAddressesOutput, error)

	DescribeAssociatedUsersRequest(*computing.DescribeAssociatedUsersInput) (*request.Request, *computing.DescribeAssociatedUsersOutput)

	DescribeAssociatedUsers(*computing.DescribeAssociatedUsersInput) (*computing.DescribeAssociatedUsersOutput, error)

	DescribeAvailabilityZonesRequest(*computing.DescribeAvailabilityZonesInput) (*request.Request, *computing.DescribeAvailabilityZonesOutput)

	DescribeAvailabilityZones(*computing.DescribeAvailabilityZonesInput) (*computing.DescribeAvailabilityZonesOutput, error)

	DescribeCustomerGatewaysRequest(*computing.DescribeCustomerGatewaysInput) (*request.Request, *computing.DescribeCustomerGatewaysOutput)

	DescribeCustomerGateways(*computing.DescribeCustomerGatewaysInput) (*computing.DescribeCustomerGatewaysOutput, error)

	DescribeDhcpOptionsRequest(*computing.DescribeDhcpOptionsInput) (*request.Request, *computing.DescribeDhcpOptionsOutput)

	DescribeDhcpOptions(*computing.DescribeDhcpOptionsInput) (*computing.DescribeDhcpOptionsOutput, error)

	DescribeImagesRequest(*computing.DescribeImagesInput) (*request.Request, *computing.DescribeImagesOutput)

	DescribeImages(*computing.DescribeImagesInput) (*computing.DescribeImagesOutput, error)

	DescribeInstanceAttributeRequest(*computing.DescribeInstanceAttributeInput) (*request.Request, *computing.DescribeInstanceAttributeOutput)

	DescribeInstanceAttribute(*computing.DescribeInstanceAttributeInput) (*computing.DescribeInstanceAttributeOutput, error)

	DescribeInstanceHealthRequest(*computing.DescribeInstanceHealthInput) (*request.Request, *computing.DescribeInstanceHealthOutput)

	DescribeInstanceHealth(*computing.DescribeInstanceHealthInput) (*computing.DescribeInstanceHealthOutput, error)

	DescribeInstancesRequest(*computing.DescribeInstancesInput) (*request.Request, *computing.DescribeInstancesOutput)

	DescribeInstances(*computing.DescribeInstancesInput) (*computing.DescribeInstancesOutput, error)

	DescribeKeyPairsRequest(*computing.DescribeKeyPairsInput) (*request.Request, *computing.DescribeKeyPairsOutput)

	DescribeKeyPairs(*computing.DescribeKeyPairsInput) (*computing.DescribeKeyPairsOutput, error)

	DescribeLoadBalancersRequest(*computing.DescribeLoadBalancersInput) (*request.Request, *computing.DescribeLoadBalancersOutput)

	DescribeLoadBalancers(*computing.DescribeLoadBalancersInput) (*computing.DescribeLoadBalancersOutput, error)

	DescribeRegionsRequest(*computing.DescribeRegionsInput) (*request.Request, *computing.DescribeRegionsOutput)

	DescribeRegions(*computing.DescribeRegionsInput) (*computing.DescribeRegionsOutput, error)

	DescribeResourcesRequest(*computing.DescribeResourcesInput) (*request.Request, *computing.DescribeResourcesOutput)

	DescribeResources(*computing.DescribeResourcesInput) (*computing.DescribeResourcesOutput, error)

	DescribeRouteTablesRequest(*computing.DescribeRouteTablesInput) (*request.Request, *computing.DescribeRouteTablesOutput)

	DescribeRouteTables(*computing.DescribeRouteTablesInput) (*computing.DescribeRouteTablesOutput, error)

	DescribeSecurityActivitiesRequest(*computing.DescribeSecurityActivitiesInput) (*request.Request, *computing.DescribeSecurityActivitiesOutput)

	DescribeSecurityActivities(*computing.DescribeSecurityActivitiesInput) (*computing.DescribeSecurityActivitiesOutput, error)

	DescribeSecurityGroupOptionRequest(*computing.DescribeSecurityGroupOptionInput) (*request.Request, *computing.DescribeSecurityGroupOptionOutput)

	DescribeSecurityGroupOption(*computing.DescribeSecurityGroupOptionInput) (*computing.DescribeSecurityGroupOptionOutput, error)

	DescribeSecurityGroupsRequest(*computing.DescribeSecurityGroupsInput) (*request.Request, *computing.DescribeSecurityGroupsOutput)

	DescribeSecurityGroups(*computing.DescribeSecurityGroupsInput) (*computing.DescribeSecurityGroupsOutput, error)

	DescribeServiceStatusRequest(*computing.DescribeServiceStatusInput) (*request.Request, *computing.DescribeServiceStatusOutput)

	DescribeServiceStatus(*computing.DescribeServiceStatusInput) (*computing.DescribeServiceStatusOutput, error)

	DescribeSslCertificateAttributeRequest(*computing.DescribeSslCertificateAttributeInput) (*request.Request, *computing.DescribeSslCertificateAttributeOutput)

	DescribeSslCertificateAttribute(*computing.DescribeSslCertificateAttributeInput) (*computing.DescribeSslCertificateAttributeOutput, error)

	DescribeSslCertificatesRequest(*computing.DescribeSslCertificatesInput) (*request.Request, *computing.DescribeSslCertificatesOutput)

	DescribeSslCertificates(*computing.DescribeSslCertificatesInput) (*computing.DescribeSslCertificatesOutput, error)

	DescribeUploadsRequest(*computing.DescribeUploadsInput) (*request.Request, *computing.DescribeUploadsOutput)

	DescribeUploads(*computing.DescribeUploadsInput) (*computing.DescribeUploadsOutput, error)

	DescribeUsageRequest(*computing.DescribeUsageInput) (*request.Request, *computing.DescribeUsageOutput)

	DescribeUsage(*computing.DescribeUsageInput) (*computing.DescribeUsageOutput, error)

	DescribeUserActivitiesRequest(*computing.DescribeUserActivitiesInput) (*request.Request, *computing.DescribeUserActivitiesOutput)

	DescribeUserActivities(*computing.DescribeUserActivitiesInput) (*computing.DescribeUserActivitiesOutput, error)

	DescribeVolumesRequest(*computing.DescribeVolumesInput) (*request.Request, *computing.DescribeVolumesOutput)

	DescribeVolumes(*computing.DescribeVolumesInput) (*computing.DescribeVolumesOutput, error)

	DescribeVpnConnectionsRequest(*computing.DescribeVpnConnectionsInput) (*request.Request, *computing.DescribeVpnConnectionsOutput)

	DescribeVpnConnections(*computing.DescribeVpnConnectionsInput) (*computing.DescribeVpnConnectionsOutput, error)

	DescribeVpnGatewaysRequest(*computing.DescribeVpnGatewaysInput) (*request.Request, *computing.DescribeVpnGatewaysOutput)

	DescribeVpnGateways(*computing.DescribeVpnGatewaysInput) (*computing.DescribeVpnGatewaysOutput, error)

	DetachVolumeRequest(*computing.DetachVolumeInput) (*request.Request, *computing.DetachVolumeOutput)

	DetachVolume(*computing.DetachVolumeInput) (*computing.DetachVolumeOutput, error)

	DisassociateAddressRequest(*computing.DisassociateAddressInput) (*request.Request, *computing.DisassociateAddressOutput)

	DisassociateAddress(*computing.DisassociateAddressInput) (*computing.DisassociateAddressOutput, error)

	DisassociateRouteTableRequest(*computing.DisassociateRouteTableInput) (*request.Request, *computing.DisassociateRouteTableOutput)

	DisassociateRouteTable(*computing.DisassociateRouteTableInput) (*computing.DisassociateRouteTableOutput, error)

	DissociateUsersRequest(*computing.DissociateUsersInput) (*request.Request, *computing.DissociateUsersOutput)

	DissociateUsers(*computing.DissociateUsersInput) (*computing.DissociateUsersOutput, error)

	DownloadSslCertificateRequest(*computing.DownloadSslCertificateInput) (*request.Request, *computing.DownloadSslCertificateOutput)

	DownloadSslCertificate(*computing.DownloadSslCertificateInput) (*computing.DownloadSslCertificateOutput, error)

	ImportInstanceRequest(*computing.ImportInstanceInput) (*request.Request, *computing.ImportInstanceOutput)

	ImportInstance(*computing.ImportInstanceInput) (*computing.ImportInstanceOutput, error)

	ImportKeyPairRequest(*computing.ImportKeyPairInput) (*request.Request, *computing.ImportKeyPairOutput)

	ImportKeyPair(*computing.ImportKeyPairInput) (*computing.ImportKeyPairOutput, error)

	ModifyImageAttributeRequest(*computing.ModifyImageAttributeInput) (*request.Request, *computing.ModifyImageAttributeOutput)

	ModifyImageAttribute(*computing.ModifyImageAttributeInput) (*computing.ModifyImageAttributeOutput, error)

	ModifyInstanceAttributeRequest(*computing.ModifyInstanceAttributeInput) (*request.Request, *computing.ModifyInstanceAttributeOutput)

	ModifyInstanceAttribute(*computing.ModifyInstanceAttributeInput) (*computing.ModifyInstanceAttributeOutput, error)

	ModifySslCertificateAttributeRequest(*computing.ModifySslCertificateAttributeInput) (*request.Request, *computing.ModifySslCertificateAttributeOutput)

	ModifySslCertificateAttribute(*computing.ModifySslCertificateAttributeInput) (*computing.ModifySslCertificateAttributeOutput, error)

	ModifyVolumeAttributeRequest(*computing.ModifyVolumeAttributeInput) (*request.Request, *computing.ModifyVolumeAttributeOutput)

	ModifyVolumeAttribute(*computing.ModifyVolumeAttributeInput) (*computing.ModifyVolumeAttributeOutput, error)

	NiftyAssociateImageRequest(*computing.NiftyAssociateImageInput) (*request.Request, *computing.NiftyAssociateImageOutput)

	NiftyAssociateImage(*computing.NiftyAssociateImageInput) (*computing.NiftyAssociateImageOutput, error)

	NiftyAssociateNatTableRequest(*computing.NiftyAssociateNatTableInput) (*request.Request, *computing.NiftyAssociateNatTableOutput)

	NiftyAssociateNatTable(*computing.NiftyAssociateNatTableInput) (*computing.NiftyAssociateNatTableOutput, error)

	NiftyAssociateRouteTableWithVpnGatewayRequest(*computing.NiftyAssociateRouteTableWithVpnGatewayInput) (*request.Request, *computing.NiftyAssociateRouteTableWithVpnGatewayOutput)

	NiftyAssociateRouteTableWithVpnGateway(*computing.NiftyAssociateRouteTableWithVpnGatewayInput) (*computing.NiftyAssociateRouteTableWithVpnGatewayOutput, error)

	NiftyCreateAlarmRequest(*computing.NiftyCreateAlarmInput) (*request.Request, *computing.NiftyCreateAlarmOutput)

	NiftyCreateAlarm(*computing.NiftyCreateAlarmInput) (*computing.NiftyCreateAlarmOutput, error)

	NiftyCreateAutoScalingGroupRequest(*computing.NiftyCreateAutoScalingGroupInput) (*request.Request, *computing.NiftyCreateAutoScalingGroupOutput)

	NiftyCreateAutoScalingGroup(*computing.NiftyCreateAutoScalingGroupInput) (*computing.NiftyCreateAutoScalingGroupOutput, error)

	NiftyCreateDhcpConfigRequest(*computing.NiftyCreateDhcpConfigInput) (*request.Request, *computing.NiftyCreateDhcpConfigOutput)

	NiftyCreateDhcpConfig(*computing.NiftyCreateDhcpConfigInput) (*computing.NiftyCreateDhcpConfigOutput, error)

	NiftyCreateDhcpIpAddressPoolRequest(*computing.NiftyCreateDhcpIpAddressPoolInput) (*request.Request, *computing.NiftyCreateDhcpIpAddressPoolOutput)

	NiftyCreateDhcpIpAddressPool(*computing.NiftyCreateDhcpIpAddressPoolInput) (*computing.NiftyCreateDhcpIpAddressPoolOutput, error)

	NiftyCreateDhcpStaticMappingRequest(*computing.NiftyCreateDhcpStaticMappingInput) (*request.Request, *computing.NiftyCreateDhcpStaticMappingOutput)

	NiftyCreateDhcpStaticMapping(*computing.NiftyCreateDhcpStaticMappingInput) (*computing.NiftyCreateDhcpStaticMappingOutput, error)

	NiftyCreateInstanceSnapshotRequest(*computing.NiftyCreateInstanceSnapshotInput) (*request.Request, *computing.NiftyCreateInstanceSnapshotOutput)

	NiftyCreateInstanceSnapshot(*computing.NiftyCreateInstanceSnapshotInput) (*computing.NiftyCreateInstanceSnapshotOutput, error)

	NiftyCreateNatRuleRequest(*computing.NiftyCreateNatRuleInput) (*request.Request, *computing.NiftyCreateNatRuleOutput)

	NiftyCreateNatRule(*computing.NiftyCreateNatRuleInput) (*computing.NiftyCreateNatRuleOutput, error)

	NiftyCreateNatTableRequest(*computing.NiftyCreateNatTableInput) (*request.Request, *computing.NiftyCreateNatTableOutput)

	NiftyCreateNatTable(*computing.NiftyCreateNatTableInput) (*computing.NiftyCreateNatTableOutput, error)

	NiftyCreatePrivateLanRequest(*computing.NiftyCreatePrivateLanInput) (*request.Request, *computing.NiftyCreatePrivateLanOutput)

	NiftyCreatePrivateLan(*computing.NiftyCreatePrivateLanInput) (*computing.NiftyCreatePrivateLanOutput, error)

	NiftyCreateRouterRequest(*computing.NiftyCreateRouterInput) (*request.Request, *computing.NiftyCreateRouterOutput)

	NiftyCreateRouter(*computing.NiftyCreateRouterInput) (*computing.NiftyCreateRouterOutput, error)

	NiftyCreateWebProxyRequest(*computing.NiftyCreateWebProxyInput) (*request.Request, *computing.NiftyCreateWebProxyOutput)

	NiftyCreateWebProxy(*computing.NiftyCreateWebProxyInput) (*computing.NiftyCreateWebProxyOutput, error)

	NiftyDeleteAlarmRequest(*computing.NiftyDeleteAlarmInput) (*request.Request, *computing.NiftyDeleteAlarmOutput)

	NiftyDeleteAlarm(*computing.NiftyDeleteAlarmInput) (*computing.NiftyDeleteAlarmOutput, error)

	NiftyDeleteAutoScalingGroupRequest(*computing.NiftyDeleteAutoScalingGroupInput) (*request.Request, *computing.NiftyDeleteAutoScalingGroupOutput)

	NiftyDeleteAutoScalingGroup(*computing.NiftyDeleteAutoScalingGroupInput) (*computing.NiftyDeleteAutoScalingGroupOutput, error)

	NiftyDeleteDhcpConfigRequest(*computing.NiftyDeleteDhcpConfigInput) (*request.Request, *computing.NiftyDeleteDhcpConfigOutput)

	NiftyDeleteDhcpConfig(*computing.NiftyDeleteDhcpConfigInput) (*computing.NiftyDeleteDhcpConfigOutput, error)

	NiftyDeleteDhcpIpAddressPoolRequest(*computing.NiftyDeleteDhcpIpAddressPoolInput) (*request.Request, *computing.NiftyDeleteDhcpIpAddressPoolOutput)

	NiftyDeleteDhcpIpAddressPool(*computing.NiftyDeleteDhcpIpAddressPoolInput) (*computing.NiftyDeleteDhcpIpAddressPoolOutput, error)

	NiftyDeleteDhcpStaticMappingRequest(*computing.NiftyDeleteDhcpStaticMappingInput) (*request.Request, *computing.NiftyDeleteDhcpStaticMappingOutput)

	NiftyDeleteDhcpStaticMapping(*computing.NiftyDeleteDhcpStaticMappingInput) (*computing.NiftyDeleteDhcpStaticMappingOutput, error)

	NiftyDeleteInstanceSnapshotRequest(*computing.NiftyDeleteInstanceSnapshotInput) (*request.Request, *computing.NiftyDeleteInstanceSnapshotOutput)

	NiftyDeleteInstanceSnapshot(*computing.NiftyDeleteInstanceSnapshotInput) (*computing.NiftyDeleteInstanceSnapshotOutput, error)

	NiftyDeleteNatRuleRequest(*computing.NiftyDeleteNatRuleInput) (*request.Request, *computing.NiftyDeleteNatRuleOutput)

	NiftyDeleteNatRule(*computing.NiftyDeleteNatRuleInput) (*computing.NiftyDeleteNatRuleOutput, error)

	NiftyDeleteNatTableRequest(*computing.NiftyDeleteNatTableInput) (*request.Request, *computing.NiftyDeleteNatTableOutput)

	NiftyDeleteNatTable(*computing.NiftyDeleteNatTableInput) (*computing.NiftyDeleteNatTableOutput, error)

	NiftyDeletePrivateLanRequest(*computing.NiftyDeletePrivateLanInput) (*request.Request, *computing.NiftyDeletePrivateLanOutput)

	NiftyDeletePrivateLan(*computing.NiftyDeletePrivateLanInput) (*computing.NiftyDeletePrivateLanOutput, error)

	NiftyDeleteRouterRequest(*computing.NiftyDeleteRouterInput) (*request.Request, *computing.NiftyDeleteRouterOutput)

	NiftyDeleteRouter(*computing.NiftyDeleteRouterInput) (*computing.NiftyDeleteRouterOutput, error)

	NiftyDeleteWebProxyRequest(*computing.NiftyDeleteWebProxyInput) (*request.Request, *computing.NiftyDeleteWebProxyOutput)

	NiftyDeleteWebProxy(*computing.NiftyDeleteWebProxyInput) (*computing.NiftyDeleteWebProxyOutput, error)

	NiftyDeregisterRoutersFromSecurityGroupRequest(*computing.NiftyDeregisterRoutersFromSecurityGroupInput) (*request.Request, *computing.NiftyDeregisterRoutersFromSecurityGroupOutput)

	NiftyDeregisterRoutersFromSecurityGroup(*computing.NiftyDeregisterRoutersFromSecurityGroupInput) (*computing.NiftyDeregisterRoutersFromSecurityGroupOutput, error)

	NiftyDeregisterVpnGatewaysFromSecurityGroupRequest(*computing.NiftyDeregisterVpnGatewaysFromSecurityGroupInput) (*request.Request, *computing.NiftyDeregisterVpnGatewaysFromSecurityGroupOutput)

	NiftyDeregisterVpnGatewaysFromSecurityGroup(*computing.NiftyDeregisterVpnGatewaysFromSecurityGroupInput) (*computing.NiftyDeregisterVpnGatewaysFromSecurityGroupOutput, error)

	NiftyDescribeAlarmHistoryRequest(*computing.NiftyDescribeAlarmHistoryInput) (*request.Request, *computing.NiftyDescribeAlarmHistoryOutput)

	NiftyDescribeAlarmHistory(*computing.NiftyDescribeAlarmHistoryInput) (*computing.NiftyDescribeAlarmHistoryOutput, error)

	NiftyDescribeAlarmRulesActivitiesRequest(*computing.NiftyDescribeAlarmRulesActivitiesInput) (*request.Request, *computing.NiftyDescribeAlarmRulesActivitiesOutput)

	NiftyDescribeAlarmRulesActivities(*computing.NiftyDescribeAlarmRulesActivitiesInput) (*computing.NiftyDescribeAlarmRulesActivitiesOutput, error)

	NiftyDescribeAlarmsRequest(*computing.NiftyDescribeAlarmsInput) (*request.Request, *computing.NiftyDescribeAlarmsOutput)

	NiftyDescribeAlarms(*computing.NiftyDescribeAlarmsInput) (*computing.NiftyDescribeAlarmsOutput, error)

	NiftyDescribeAlarmsPartitionsRequest(*computing.NiftyDescribeAlarmsPartitionsInput) (*request.Request, *computing.NiftyDescribeAlarmsPartitionsOutput)

	NiftyDescribeAlarmsPartitions(*computing.NiftyDescribeAlarmsPartitionsInput) (*computing.NiftyDescribeAlarmsPartitionsOutput, error)

	NiftyDescribeAutoScalingGroupsRequest(*computing.NiftyDescribeAutoScalingGroupsInput) (*request.Request, *computing.NiftyDescribeAutoScalingGroupsOutput)

	NiftyDescribeAutoScalingGroups(*computing.NiftyDescribeAutoScalingGroupsInput) (*computing.NiftyDescribeAutoScalingGroupsOutput, error)

	NiftyDescribeCorporateInfoForCertificateRequest(*computing.NiftyDescribeCorporateInfoForCertificateInput) (*request.Request, *computing.NiftyDescribeCorporateInfoForCertificateOutput)

	NiftyDescribeCorporateInfoForCertificate(*computing.NiftyDescribeCorporateInfoForCertificateInput) (*computing.NiftyDescribeCorporateInfoForCertificateOutput, error)

	NiftyDescribeDhcpConfigsRequest(*computing.NiftyDescribeDhcpConfigsInput) (*request.Request, *computing.NiftyDescribeDhcpConfigsOutput)

	NiftyDescribeDhcpConfigs(*computing.NiftyDescribeDhcpConfigsInput) (*computing.NiftyDescribeDhcpConfigsOutput, error)

	NiftyDescribeDhcpStatusRequest(*computing.NiftyDescribeDhcpStatusInput) (*request.Request, *computing.NiftyDescribeDhcpStatusOutput)

	NiftyDescribeDhcpStatus(*computing.NiftyDescribeDhcpStatusInput) (*computing.NiftyDescribeDhcpStatusOutput, error)

	NiftyDescribeInstanceSnapshotsRequest(*computing.NiftyDescribeInstanceSnapshotsInput) (*request.Request, *computing.NiftyDescribeInstanceSnapshotsOutput)

	NiftyDescribeInstanceSnapshots(*computing.NiftyDescribeInstanceSnapshotsInput) (*computing.NiftyDescribeInstanceSnapshotsOutput, error)

	NiftyDescribeNatTablesRequest(*computing.NiftyDescribeNatTablesInput) (*request.Request, *computing.NiftyDescribeNatTablesOutput)

	NiftyDescribeNatTables(*computing.NiftyDescribeNatTablesInput) (*computing.NiftyDescribeNatTablesOutput, error)

	NiftyDescribePerformanceChartRequest(*computing.NiftyDescribePerformanceChartInput) (*request.Request, *computing.NiftyDescribePerformanceChartOutput)

	NiftyDescribePerformanceChart(*computing.NiftyDescribePerformanceChartInput) (*computing.NiftyDescribePerformanceChartOutput, error)

	NiftyDescribePrivateLansRequest(*computing.NiftyDescribePrivateLansInput) (*request.Request, *computing.NiftyDescribePrivateLansOutput)

	NiftyDescribePrivateLans(*computing.NiftyDescribePrivateLansInput) (*computing.NiftyDescribePrivateLansOutput, error)

	NiftyDescribeRoutersRequest(*computing.NiftyDescribeRoutersInput) (*request.Request, *computing.NiftyDescribeRoutersOutput)

	NiftyDescribeRouters(*computing.NiftyDescribeRoutersInput) (*computing.NiftyDescribeRoutersOutput, error)

	NiftyDescribeScalingActivitiesRequest(*computing.NiftyDescribeScalingActivitiesInput) (*request.Request, *computing.NiftyDescribeScalingActivitiesOutput)

	NiftyDescribeScalingActivities(*computing.NiftyDescribeScalingActivitiesInput) (*computing.NiftyDescribeScalingActivitiesOutput, error)

	NiftyDescribeVpnGatewayActivitiesRequest(*computing.NiftyDescribeVpnGatewayActivitiesInput) (*request.Request, *computing.NiftyDescribeVpnGatewayActivitiesOutput)

	NiftyDescribeVpnGatewayActivities(*computing.NiftyDescribeVpnGatewayActivitiesInput) (*computing.NiftyDescribeVpnGatewayActivitiesOutput, error)

	NiftyDescribeWebProxiesRequest(*computing.NiftyDescribeWebProxiesInput) (*request.Request, *computing.NiftyDescribeWebProxiesOutput)

	NiftyDescribeWebProxies(*computing.NiftyDescribeWebProxiesInput) (*computing.NiftyDescribeWebProxiesOutput, error)

	NiftyDisableDhcpRequest(*computing.NiftyDisableDhcpInput) (*request.Request, *computing.NiftyDisableDhcpOutput)

	NiftyDisableDhcp(*computing.NiftyDisableDhcpInput) (*computing.NiftyDisableDhcpOutput, error)

	NiftyDisassociateNatTableRequest(*computing.NiftyDisassociateNatTableInput) (*request.Request, *computing.NiftyDisassociateNatTableOutput)

	NiftyDisassociateNatTable(*computing.NiftyDisassociateNatTableInput) (*computing.NiftyDisassociateNatTableOutput, error)

	NiftyDisassociateRouteTableFromVpnGatewayRequest(*computing.NiftyDisassociateRouteTableFromVpnGatewayInput) (*request.Request, *computing.NiftyDisassociateRouteTableFromVpnGatewayOutput)

	NiftyDisassociateRouteTableFromVpnGateway(*computing.NiftyDisassociateRouteTableFromVpnGatewayInput) (*computing.NiftyDisassociateRouteTableFromVpnGatewayOutput, error)

	NiftyEnableDhcpRequest(*computing.NiftyEnableDhcpInput) (*request.Request, *computing.NiftyEnableDhcpOutput)

	NiftyEnableDhcp(*computing.NiftyEnableDhcpInput) (*computing.NiftyEnableDhcpOutput, error)

	NiftyModifyAddressAttributeRequest(*computing.NiftyModifyAddressAttributeInput) (*request.Request, *computing.NiftyModifyAddressAttributeOutput)

	NiftyModifyAddressAttribute(*computing.NiftyModifyAddressAttributeInput) (*computing.NiftyModifyAddressAttributeOutput, error)

	NiftyModifyCustomerGatewayAttributeRequest(*computing.NiftyModifyCustomerGatewayAttributeInput) (*request.Request, *computing.NiftyModifyCustomerGatewayAttributeOutput)

	NiftyModifyCustomerGatewayAttribute(*computing.NiftyModifyCustomerGatewayAttributeInput) (*computing.NiftyModifyCustomerGatewayAttributeOutput, error)

	NiftyModifyInstanceSnapshotAttributeRequest(*computing.NiftyModifyInstanceSnapshotAttributeInput) (*request.Request, *computing.NiftyModifyInstanceSnapshotAttributeOutput)

	NiftyModifyInstanceSnapshotAttribute(*computing.NiftyModifyInstanceSnapshotAttributeInput) (*computing.NiftyModifyInstanceSnapshotAttributeOutput, error)

	NiftyModifyKeyPairAttributeRequest(*computing.NiftyModifyKeyPairAttributeInput) (*request.Request, *computing.NiftyModifyKeyPairAttributeOutput)

	NiftyModifyKeyPairAttribute(*computing.NiftyModifyKeyPairAttributeInput) (*computing.NiftyModifyKeyPairAttributeOutput, error)

	NiftyModifyPrivateLanAttributeRequest(*computing.NiftyModifyPrivateLanAttributeInput) (*request.Request, *computing.NiftyModifyPrivateLanAttributeOutput)

	NiftyModifyPrivateLanAttribute(*computing.NiftyModifyPrivateLanAttributeInput) (*computing.NiftyModifyPrivateLanAttributeOutput, error)

	NiftyModifyRouterAttributeRequest(*computing.NiftyModifyRouterAttributeInput) (*request.Request, *computing.NiftyModifyRouterAttributeOutput)

	NiftyModifyRouterAttribute(*computing.NiftyModifyRouterAttributeInput) (*computing.NiftyModifyRouterAttributeOutput, error)

	NiftyModifyVpnGatewayAttributeRequest(*computing.NiftyModifyVpnGatewayAttributeInput) (*request.Request, *computing.NiftyModifyVpnGatewayAttributeOutput)

	NiftyModifyVpnGatewayAttribute(*computing.NiftyModifyVpnGatewayAttributeInput) (*computing.NiftyModifyVpnGatewayAttributeOutput, error)

	NiftyModifyWebProxyAttributeRequest(*computing.NiftyModifyWebProxyAttributeInput) (*request.Request, *computing.NiftyModifyWebProxyAttributeOutput)

	NiftyModifyWebProxyAttribute(*computing.NiftyModifyWebProxyAttributeInput) (*computing.NiftyModifyWebProxyAttributeOutput, error)

	NiftyRebootRoutersRequest(*computing.NiftyRebootRoutersInput) (*request.Request, *computing.NiftyRebootRoutersOutput)

	NiftyRebootRouters(*computing.NiftyRebootRoutersInput) (*computing.NiftyRebootRoutersOutput, error)

	NiftyRebootVpnGatewaysRequest(*computing.NiftyRebootVpnGatewaysInput) (*request.Request, *computing.NiftyRebootVpnGatewaysOutput)

	NiftyRebootVpnGateways(*computing.NiftyRebootVpnGatewaysInput) (*computing.NiftyRebootVpnGatewaysOutput, error)

	NiftyRegisterRoutersWithSecurityGroupRequest(*computing.NiftyRegisterRoutersWithSecurityGroupInput) (*request.Request, *computing.NiftyRegisterRoutersWithSecurityGroupOutput)

	NiftyRegisterRoutersWithSecurityGroup(*computing.NiftyRegisterRoutersWithSecurityGroupInput) (*computing.NiftyRegisterRoutersWithSecurityGroupOutput, error)

	NiftyRegisterVpnGatewaysWithSecurityGroupRequest(*computing.NiftyRegisterVpnGatewaysWithSecurityGroupInput) (*request.Request, *computing.NiftyRegisterVpnGatewaysWithSecurityGroupOutput)

	NiftyRegisterVpnGatewaysWithSecurityGroup(*computing.NiftyRegisterVpnGatewaysWithSecurityGroupInput) (*computing.NiftyRegisterVpnGatewaysWithSecurityGroupOutput, error)

	NiftyReleaseRouterBackupStateRequest(*computing.NiftyReleaseRouterBackupStateInput) (*request.Request, *computing.NiftyReleaseRouterBackupStateOutput)

	NiftyReleaseRouterBackupState(*computing.NiftyReleaseRouterBackupStateInput) (*computing.NiftyReleaseRouterBackupStateOutput, error)

	NiftyReleaseVpnGatewayBackupStateRequest(*computing.NiftyReleaseVpnGatewayBackupStateInput) (*request.Request, *computing.NiftyReleaseVpnGatewayBackupStateOutput)

	NiftyReleaseVpnGatewayBackupState(*computing.NiftyReleaseVpnGatewayBackupStateInput) (*computing.NiftyReleaseVpnGatewayBackupStateOutput, error)

	NiftyReplaceDhcpConfigRequest(*computing.NiftyReplaceDhcpConfigInput) (*request.Request, *computing.NiftyReplaceDhcpConfigOutput)

	NiftyReplaceDhcpConfig(*computing.NiftyReplaceDhcpConfigInput) (*computing.NiftyReplaceDhcpConfigOutput, error)

	NiftyReplaceDhcpOptionRequest(*computing.NiftyReplaceDhcpOptionInput) (*request.Request, *computing.NiftyReplaceDhcpOptionOutput)

	NiftyReplaceDhcpOption(*computing.NiftyReplaceDhcpOptionInput) (*computing.NiftyReplaceDhcpOptionOutput, error)

	NiftyReplaceNatRuleRequest(*computing.NiftyReplaceNatRuleInput) (*request.Request, *computing.NiftyReplaceNatRuleOutput)

	NiftyReplaceNatRule(*computing.NiftyReplaceNatRuleInput) (*computing.NiftyReplaceNatRuleOutput, error)

	NiftyReplaceNatTableAssociationRequest(*computing.NiftyReplaceNatTableAssociationInput) (*request.Request, *computing.NiftyReplaceNatTableAssociationOutput)

	NiftyReplaceNatTableAssociation(*computing.NiftyReplaceNatTableAssociationInput) (*computing.NiftyReplaceNatTableAssociationOutput, error)

	NiftyReplaceRouteTableAssociationWithVpnGatewayRequest(*computing.NiftyReplaceRouteTableAssociationWithVpnGatewayInput) (*request.Request, *computing.NiftyReplaceRouteTableAssociationWithVpnGatewayOutput)

	NiftyReplaceRouteTableAssociationWithVpnGateway(*computing.NiftyReplaceRouteTableAssociationWithVpnGatewayInput) (*computing.NiftyReplaceRouteTableAssociationWithVpnGatewayOutput, error)

	NiftyReplaceRouterLatestVersionRequest(*computing.NiftyReplaceRouterLatestVersionInput) (*request.Request, *computing.NiftyReplaceRouterLatestVersionOutput)

	NiftyReplaceRouterLatestVersion(*computing.NiftyReplaceRouterLatestVersionInput) (*computing.NiftyReplaceRouterLatestVersionOutput, error)

	NiftyReplaceVpnGatewayLatestVersionRequest(*computing.NiftyReplaceVpnGatewayLatestVersionInput) (*request.Request, *computing.NiftyReplaceVpnGatewayLatestVersionOutput)

	NiftyReplaceVpnGatewayLatestVersion(*computing.NiftyReplaceVpnGatewayLatestVersionInput) (*computing.NiftyReplaceVpnGatewayLatestVersionOutput, error)

	NiftyRestoreInstanceSnapshotRequest(*computing.NiftyRestoreInstanceSnapshotInput) (*request.Request, *computing.NiftyRestoreInstanceSnapshotOutput)

	NiftyRestoreInstanceSnapshot(*computing.NiftyRestoreInstanceSnapshotInput) (*computing.NiftyRestoreInstanceSnapshotOutput, error)

	NiftyRestoreRouterPreviousVersionRequest(*computing.NiftyRestoreRouterPreviousVersionInput) (*request.Request, *computing.NiftyRestoreRouterPreviousVersionOutput)

	NiftyRestoreRouterPreviousVersion(*computing.NiftyRestoreRouterPreviousVersionInput) (*computing.NiftyRestoreRouterPreviousVersionOutput, error)

	NiftyRestoreVpnGatewayPreviousVersionRequest(*computing.NiftyRestoreVpnGatewayPreviousVersionInput) (*request.Request, *computing.NiftyRestoreVpnGatewayPreviousVersionOutput)

	NiftyRestoreVpnGatewayPreviousVersion(*computing.NiftyRestoreVpnGatewayPreviousVersionInput) (*computing.NiftyRestoreVpnGatewayPreviousVersionOutput, error)

	NiftyRetryImportInstanceRequest(*computing.NiftyRetryImportInstanceInput) (*request.Request, *computing.NiftyRetryImportInstanceOutput)

	NiftyRetryImportInstance(*computing.NiftyRetryImportInstanceInput) (*computing.NiftyRetryImportInstanceOutput, error)

	NiftyUpdateAlarmRequest(*computing.NiftyUpdateAlarmInput) (*request.Request, *computing.NiftyUpdateAlarmOutput)

	NiftyUpdateAlarm(*computing.NiftyUpdateAlarmInput) (*computing.NiftyUpdateAlarmOutput, error)

	NiftyUpdateAutoScalingGroupRequest(*computing.NiftyUpdateAutoScalingGroupInput) (*request.Request, *computing.NiftyUpdateAutoScalingGroupOutput)

	NiftyUpdateAutoScalingGroup(*computing.NiftyUpdateAutoScalingGroupInput) (*computing.NiftyUpdateAutoScalingGroupOutput, error)

	NiftyUpdateInstanceNetworkInterfacesRequest(*computing.NiftyUpdateInstanceNetworkInterfacesInput) (*request.Request, *computing.NiftyUpdateInstanceNetworkInterfacesOutput)

	NiftyUpdateInstanceNetworkInterfaces(*computing.NiftyUpdateInstanceNetworkInterfacesInput) (*computing.NiftyUpdateInstanceNetworkInterfacesOutput, error)

	NiftyUpdateRouterNetworkInterfacesRequest(*computing.NiftyUpdateRouterNetworkInterfacesInput) (*request.Request, *computing.NiftyUpdateRouterNetworkInterfacesOutput)

	NiftyUpdateRouterNetworkInterfaces(*computing.NiftyUpdateRouterNetworkInterfacesInput) (*computing.NiftyUpdateRouterNetworkInterfacesOutput, error)

	NiftyUpdateVpnGatewayNetworkInterfacesRequest(*computing.NiftyUpdateVpnGatewayNetworkInterfacesInput) (*request.Request, *computing.NiftyUpdateVpnGatewayNetworkInterfacesOutput)

	NiftyUpdateVpnGatewayNetworkInterfaces(*computing.NiftyUpdateVpnGatewayNetworkInterfacesInput) (*computing.NiftyUpdateVpnGatewayNetworkInterfacesOutput, error)

	RebootInstancesRequest(*computing.RebootInstancesInput) (*request.Request, *computing.RebootInstancesOutput)

	RebootInstances(*computing.RebootInstancesInput) (*computing.RebootInstancesOutput, error)

	RegisterCorporateInfoForCertificateRequest(*computing.RegisterCorporateInfoForCertificateInput) (*request.Request, *computing.RegisterCorporateInfoForCertificateOutput)

	RegisterCorporateInfoForCertificate(*computing.RegisterCorporateInfoForCertificateInput) (*computing.RegisterCorporateInfoForCertificateOutput, error)

	RegisterInstancesWithLoadBalancerRequest(*computing.RegisterInstancesWithLoadBalancerInput) (*request.Request, *computing.RegisterInstancesWithLoadBalancerOutput)

	RegisterInstancesWithLoadBalancer(*computing.RegisterInstancesWithLoadBalancerInput) (*computing.RegisterInstancesWithLoadBalancerOutput, error)

	RegisterInstancesWithSecurityGroupRequest(*computing.RegisterInstancesWithSecurityGroupInput) (*request.Request, *computing.RegisterInstancesWithSecurityGroupOutput)

	RegisterInstancesWithSecurityGroup(*computing.RegisterInstancesWithSecurityGroupInput) (*computing.RegisterInstancesWithSecurityGroupOutput, error)

	RegisterPortWithLoadBalancerRequest(*computing.RegisterPortWithLoadBalancerInput) (*request.Request, *computing.RegisterPortWithLoadBalancerOutput)

	RegisterPortWithLoadBalancer(*computing.RegisterPortWithLoadBalancerInput) (*computing.RegisterPortWithLoadBalancerOutput, error)

	ReleaseAddressRequest(*computing.ReleaseAddressInput) (*request.Request, *computing.ReleaseAddressOutput)

	ReleaseAddress(*computing.ReleaseAddressInput) (*computing.ReleaseAddressOutput, error)

	ReplaceRouteRequest(*computing.ReplaceRouteInput) (*request.Request, *computing.ReplaceRouteOutput)

	ReplaceRoute(*computing.ReplaceRouteInput) (*computing.ReplaceRouteOutput, error)

	ReplaceRouteTableAssociationRequest(*computing.ReplaceRouteTableAssociationInput) (*request.Request, *computing.ReplaceRouteTableAssociationOutput)

	ReplaceRouteTableAssociation(*computing.ReplaceRouteTableAssociationInput) (*computing.ReplaceRouteTableAssociationOutput, error)

	RevokeSecurityGroupIngressRequest(*computing.RevokeSecurityGroupIngressInput) (*request.Request, *computing.RevokeSecurityGroupIngressOutput)

	RevokeSecurityGroupIngress(*computing.RevokeSecurityGroupIngressInput) (*computing.RevokeSecurityGroupIngressOutput, error)

	RunInstancesRequest(*computing.RunInstancesInput) (*request.Request, *computing.RunInstancesOutput)

	RunInstances(*computing.RunInstancesInput) (*computing.RunInstancesOutput, error)

	SetFilterForLoadBalancerRequest(*computing.SetFilterForLoadBalancerInput) (*request.Request, *computing.SetFilterForLoadBalancerOutput)

	SetFilterForLoadBalancer(*computing.SetFilterForLoadBalancerInput) (*computing.SetFilterForLoadBalancerOutput, error)

	StartInstancesRequest(*computing.StartInstancesInput) (*request.Request, *computing.StartInstancesOutput)

	StartInstances(*computing.StartInstancesInput) (*computing.StartInstancesOutput, error)

	StopInstancesRequest(*computing.StopInstancesInput) (*request.Request, *computing.StopInstancesOutput)

	StopInstances(*computing.StopInstancesInput) (*computing.StopInstancesOutput, error)

	TerminateInstancesRequest(*computing.TerminateInstancesInput) (*request.Request, *computing.TerminateInstancesOutput)

	TerminateInstances(*computing.TerminateInstancesInput) (*computing.TerminateInstancesOutput, error)

	UpdateLoadBalancerRequest(*computing.UpdateLoadBalancerInput) (*request.Request, *computing.UpdateLoadBalancerOutput)

	UpdateLoadBalancer(*computing.UpdateLoadBalancerInput) (*computing.UpdateLoadBalancerOutput, error)

	UpdateLoadBalancerOptionRequest(*computing.UpdateLoadBalancerOptionInput) (*request.Request, *computing.UpdateLoadBalancerOptionOutput)

	UpdateLoadBalancerOption(*computing.UpdateLoadBalancerOptionInput) (*computing.UpdateLoadBalancerOptionOutput, error)

	UpdateSecurityGroupRequest(*computing.UpdateSecurityGroupInput) (*request.Request, *computing.UpdateSecurityGroupOutput)

	UpdateSecurityGroup(*computing.UpdateSecurityGroupInput) (*computing.UpdateSecurityGroupOutput, error)

	UpdateSecurityGroupOptionRequest(*computing.UpdateSecurityGroupOptionInput) (*request.Request, *computing.UpdateSecurityGroupOptionOutput)

	UpdateSecurityGroupOption(*computing.UpdateSecurityGroupOptionInput) (*computing.UpdateSecurityGroupOptionOutput, error)

	UploadSslCertificateRequest(*computing.UploadSslCertificateInput) (*request.Request, *computing.UploadSslCertificateOutput)

	UploadSslCertificate(*computing.UploadSslCertificateInput) (*computing.UploadSslCertificateOutput, error)
}

var _ computingAPI = (*computing.computing)(nil)
