// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package storage_test

import (
	"bytes"
	"fmt"
	"time"

	"github.com/tily/sdk-go/aws"
	"github.com/tily/sdk-go/aws/session"
	"github.com/tily/sdk-go/service/storage"
)

var _ time.Duration
var _ bytes.Buffer

func Examplestorage_AbortMultipartUpload() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.AbortMultipartUploadInput{
		Bucket:       aws.String("BucketName"),        // Required
		Key:          aws.String("ObjectKey"),         // Required
		UploadId:     aws.String("MultipartUploadId"), // Required
		RequestPayer: aws.String("RequestPayer"),
	}
	resp, err := svc.AbortMultipartUpload(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_CompleteMultipartUpload() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.CompleteMultipartUploadInput{
		Bucket:   aws.String("BucketName"),        // Required
		Key:      aws.String("ObjectKey"),         // Required
		UploadId: aws.String("MultipartUploadId"), // Required
		MultipartUpload: &storage.CompletedMultipartUpload{
			Parts: []*storage.CompletedPart{
				{ // Required
					ETag:       aws.String("ETag"),
					PartNumber: aws.Int64(1),
				},
				// More values...
			},
		},
		RequestPayer: aws.String("RequestPayer"),
	}
	resp, err := svc.CompleteMultipartUpload(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_CopyObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.CopyObjectInput{
		Bucket:                         aws.String("BucketName"), // Required
		CopySource:                     aws.String("CopySource"), // Required
		Key:                            aws.String("ObjectKey"),  // Required
		ACL:                            aws.String("ObjectCannedACL"),
		CacheControl:                   aws.String("CacheControl"),
		ContentDisposition:             aws.String("ContentDisposition"),
		ContentEncoding:                aws.String("ContentEncoding"),
		ContentLanguage:                aws.String("ContentLanguage"),
		ContentType:                    aws.String("ContentType"),
		CopySourceIfMatch:              aws.String("CopySourceIfMatch"),
		CopySourceIfModifiedSince:      aws.Time(time.Now()),
		CopySourceIfNoneMatch:          aws.String("CopySourceIfNoneMatch"),
		CopySourceIfUnmodifiedSince:    aws.Time(time.Now()),
		CopySourceSSECustomerAlgorithm: aws.String("CopySourceSSECustomerAlgorithm"),
		CopySourceSSECustomerKey:       aws.String("CopySourceSSECustomerKey"),
		CopySourceSSECustomerKeyMD5:    aws.String("CopySourceSSECustomerKeyMD5"),
		Expires:                        aws.Time(time.Now()),
		GrantFullControl:               aws.String("GrantFullControl"),
		GrantRead:                      aws.String("GrantRead"),
		GrantReadACP:                   aws.String("GrantReadACP"),
		GrantWriteACP:                  aws.String("GrantWriteACP"),
		Metadata: map[string]*string{
			"Key": aws.String("MetadataValue"), // Required
			// More values...
		},
		MetadataDirective:       aws.String("MetadataDirective"),
		RequestPayer:            aws.String("RequestPayer"),
		SSECustomerAlgorithm:    aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:          aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:       aws.String("SSECustomerKeyMD5"),
		SSEKMSKeyId:             aws.String("SSEKMSKeyId"),
		ServerSideEncryption:    aws.String("ServerSideEncryption"),
		StorageClass:            aws.String("Class"),
		Tagging:                 aws.String("TaggingHeader"),
		TaggingDirective:        aws.String("TaggingDirective"),
		WebsiteRedirectLocation: aws.String("WebsiteRedirectLocation"),
	}
	resp, err := svc.CopyObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_CreateBucket() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.CreateBucketInput{
		Bucket: aws.String("BucketName"), // Required
		ACL:    aws.String("BucketCannedACL"),
		CreateBucketConfiguration: &storage.CreateBucketConfiguration{
			LocationConstraint: aws.String("BucketLocationConstraint"),
		},
		GrantFullControl: aws.String("GrantFullControl"),
		GrantRead:        aws.String("GrantRead"),
		GrantReadACP:     aws.String("GrantReadACP"),
		GrantWrite:       aws.String("GrantWrite"),
		GrantWriteACP:    aws.String("GrantWriteACP"),
	}
	resp, err := svc.CreateBucket(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_CreateMultipartUpload() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.CreateMultipartUploadInput{
		Bucket:             aws.String("BucketName"), // Required
		Key:                aws.String("ObjectKey"),  // Required
		ACL:                aws.String("ObjectCannedACL"),
		CacheControl:       aws.String("CacheControl"),
		ContentDisposition: aws.String("ContentDisposition"),
		ContentEncoding:    aws.String("ContentEncoding"),
		ContentLanguage:    aws.String("ContentLanguage"),
		ContentType:        aws.String("ContentType"),
		Expires:            aws.Time(time.Now()),
		GrantFullControl:   aws.String("GrantFullControl"),
		GrantRead:          aws.String("GrantRead"),
		GrantReadACP:       aws.String("GrantReadACP"),
		GrantWriteACP:      aws.String("GrantWriteACP"),
		Metadata: map[string]*string{
			"Key": aws.String("MetadataValue"), // Required
			// More values...
		},
		RequestPayer:            aws.String("RequestPayer"),
		SSECustomerAlgorithm:    aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:          aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:       aws.String("SSECustomerKeyMD5"),
		SSEKMSKeyId:             aws.String("SSEKMSKeyId"),
		ServerSideEncryption:    aws.String("ServerSideEncryption"),
		StorageClass:            aws.String("Class"),
		WebsiteRedirectLocation: aws.String("WebsiteRedirectLocation"),
	}
	resp, err := svc.CreateMultipartUpload(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucket() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucket(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketAnalyticsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketAnalyticsConfigurationInput{
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("AnalyticsId"), // Required
	}
	resp, err := svc.DeleteBucketAnalyticsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketCors() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketCorsInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketCors(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketInventoryConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketInventoryConfigurationInput{
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("InventoryId"), // Required
	}
	resp, err := svc.DeleteBucketInventoryConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketLifecycle() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketLifecycleInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketLifecycle(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketMetricsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketMetricsConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
		Id:     aws.String("MetricsId"),  // Required
	}
	resp, err := svc.DeleteBucketMetricsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketPolicy() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketPolicyInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketPolicy(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketReplication() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketReplicationInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketReplication(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketTaggingInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteBucketWebsite() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteBucketWebsiteInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.DeleteBucketWebsite(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteObjectInput{
		Bucket:       aws.String("BucketName"), // Required
		Key:          aws.String("ObjectKey"),  // Required
		MFA:          aws.String("MFA"),
		RequestPayer: aws.String("RequestPayer"),
		VersionId:    aws.String("ObjectVersionId"),
	}
	resp, err := svc.DeleteObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteObjectTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteObjectTaggingInput{
		Bucket:    aws.String("BucketName"), // Required
		Key:       aws.String("ObjectKey"),  // Required
		VersionId: aws.String("ObjectVersionId"),
	}
	resp, err := svc.DeleteObjectTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_DeleteObjects() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.DeleteObjectsInput{
		Bucket: aws.String("BucketName"), // Required
		Delete: &storage.Delete{ // Required
			Objects: []*storage.ObjectIdentifier{ // Required
				{ // Required
					Key:       aws.String("ObjectKey"), // Required
					VersionId: aws.String("ObjectVersionId"),
				},
				// More values...
			},
			Quiet: aws.Bool(true),
		},
		MFA:          aws.String("MFA"),
		RequestPayer: aws.String("RequestPayer"),
	}
	resp, err := svc.DeleteObjects(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketAccelerateConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketAccelerateConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketAccelerateConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketAcl() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketAclInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketAcl(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketAnalyticsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketAnalyticsConfigurationInput{
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("AnalyticsId"), // Required
	}
	resp, err := svc.GetBucketAnalyticsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketCors() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketCorsInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketCors(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketInventoryConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketInventoryConfigurationInput{
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("InventoryId"), // Required
	}
	resp, err := svc.GetBucketInventoryConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketLifecycle() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketLifecycleInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketLifecycle(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketLifecycleConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketLifecycleConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketLifecycleConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketLocation() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketLocationInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketLocation(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketLogging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketLoggingInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketLogging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketMetricsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketMetricsConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
		Id:     aws.String("MetricsId"),  // Required
	}
	resp, err := svc.GetBucketMetricsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketNotification() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketNotificationConfigurationRequest{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketNotification(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketNotificationConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketNotificationConfigurationRequest{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketNotificationConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketPolicy() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketPolicyInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketPolicy(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketReplication() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketReplicationInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketReplication(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketRequestPayment() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketRequestPaymentInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketRequestPayment(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketTaggingInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketVersioning() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketVersioningInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketVersioning(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetBucketWebsite() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetBucketWebsiteInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.GetBucketWebsite(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetObjectInput{
		Bucket:                     aws.String("BucketName"), // Required
		Key:                        aws.String("ObjectKey"),  // Required
		IfMatch:                    aws.String("IfMatch"),
		IfModifiedSince:            aws.Time(time.Now()),
		IfNoneMatch:                aws.String("IfNoneMatch"),
		IfUnmodifiedSince:          aws.Time(time.Now()),
		PartNumber:                 aws.Int64(1),
		Range:                      aws.String("Range"),
		RequestPayer:               aws.String("RequestPayer"),
		ResponseCacheControl:       aws.String("ResponseCacheControl"),
		ResponseContentDisposition: aws.String("ResponseContentDisposition"),
		ResponseContentEncoding:    aws.String("ResponseContentEncoding"),
		ResponseContentLanguage:    aws.String("ResponseContentLanguage"),
		ResponseContentType:        aws.String("ResponseContentType"),
		ResponseExpires:            aws.Time(time.Now()),
		SSECustomerAlgorithm:       aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:             aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:          aws.String("SSECustomerKeyMD5"),
		VersionId:                  aws.String("ObjectVersionId"),
	}
	resp, err := svc.GetObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetObjectAcl() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetObjectAclInput{
		Bucket:       aws.String("BucketName"), // Required
		Key:          aws.String("ObjectKey"),  // Required
		RequestPayer: aws.String("RequestPayer"),
		VersionId:    aws.String("ObjectVersionId"),
	}
	resp, err := svc.GetObjectAcl(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetObjectTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetObjectTaggingInput{
		Bucket:    aws.String("BucketName"), // Required
		Key:       aws.String("ObjectKey"),  // Required
		VersionId: aws.String("ObjectVersionId"),
	}
	resp, err := svc.GetObjectTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_GetObjectTorrent() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.GetObjectTorrentInput{
		Bucket:       aws.String("BucketName"), // Required
		Key:          aws.String("ObjectKey"),  // Required
		RequestPayer: aws.String("RequestPayer"),
	}
	resp, err := svc.GetObjectTorrent(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_HeadBucket() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.HeadBucketInput{
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.HeadBucket(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_HeadObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.HeadObjectInput{
		Bucket:               aws.String("BucketName"), // Required
		Key:                  aws.String("ObjectKey"),  // Required
		IfMatch:              aws.String("IfMatch"),
		IfModifiedSince:      aws.Time(time.Now()),
		IfNoneMatch:          aws.String("IfNoneMatch"),
		IfUnmodifiedSince:    aws.Time(time.Now()),
		PartNumber:           aws.Int64(1),
		Range:                aws.String("Range"),
		RequestPayer:         aws.String("RequestPayer"),
		SSECustomerAlgorithm: aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:       aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:    aws.String("SSECustomerKeyMD5"),
		VersionId:            aws.String("ObjectVersionId"),
	}
	resp, err := svc.HeadObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListBucketAnalyticsConfigurations() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListBucketAnalyticsConfigurationsInput{
		Bucket:            aws.String("BucketName"), // Required
		ContinuationToken: aws.String("Token"),
	}
	resp, err := svc.ListBucketAnalyticsConfigurations(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListBucketInventoryConfigurations() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListBucketInventoryConfigurationsInput{
		Bucket:            aws.String("BucketName"), // Required
		ContinuationToken: aws.String("Token"),
	}
	resp, err := svc.ListBucketInventoryConfigurations(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListBucketMetricsConfigurations() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListBucketMetricsConfigurationsInput{
		Bucket:            aws.String("BucketName"), // Required
		ContinuationToken: aws.String("Token"),
	}
	resp, err := svc.ListBucketMetricsConfigurations(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListBuckets() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	var params *storage.ListBucketsInput
	resp, err := svc.ListBuckets(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListMultipartUploads() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListMultipartUploadsInput{
		Bucket:         aws.String("BucketName"), // Required
		Delimiter:      aws.String("Delimiter"),
		EncodingType:   aws.String("EncodingType"),
		KeyMarker:      aws.String("KeyMarker"),
		MaxUploads:     aws.Int64(1),
		Prefix:         aws.String("Prefix"),
		UploadIdMarker: aws.String("UploadIdMarker"),
	}
	resp, err := svc.ListMultipartUploads(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListObjectVersions() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListObjectVersionsInput{
		Bucket:          aws.String("BucketName"), // Required
		Delimiter:       aws.String("Delimiter"),
		EncodingType:    aws.String("EncodingType"),
		KeyMarker:       aws.String("KeyMarker"),
		MaxKeys:         aws.Int64(1),
		Prefix:          aws.String("Prefix"),
		VersionIdMarker: aws.String("VersionIdMarker"),
	}
	resp, err := svc.ListObjectVersions(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListObjects() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListObjectsInput{
		Bucket:       aws.String("BucketName"), // Required
		Delimiter:    aws.String("Delimiter"),
		EncodingType: aws.String("EncodingType"),
		Marker:       aws.String("Marker"),
		MaxKeys:      aws.Int64(1),
		Prefix:       aws.String("Prefix"),
		RequestPayer: aws.String("RequestPayer"),
	}
	resp, err := svc.ListObjects(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListObjectsV2() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListObjectsV2Input{
		Bucket:            aws.String("BucketName"), // Required
		ContinuationToken: aws.String("Token"),
		Delimiter:         aws.String("Delimiter"),
		EncodingType:      aws.String("EncodingType"),
		FetchOwner:        aws.Bool(true),
		MaxKeys:           aws.Int64(1),
		Prefix:            aws.String("Prefix"),
		RequestPayer:      aws.String("RequestPayer"),
		StartAfter:        aws.String("StartAfter"),
	}
	resp, err := svc.ListObjectsV2(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_ListParts() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.ListPartsInput{
		Bucket:           aws.String("BucketName"),        // Required
		Key:              aws.String("ObjectKey"),         // Required
		UploadId:         aws.String("MultipartUploadId"), // Required
		MaxParts:         aws.Int64(1),
		PartNumberMarker: aws.Int64(1),
		RequestPayer:     aws.String("RequestPayer"),
	}
	resp, err := svc.ListParts(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketAccelerateConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketAccelerateConfigurationInput{
		AccelerateConfiguration: &storage.AccelerateConfiguration{ // Required
			Status: aws.String("BucketAccelerateStatus"),
		},
		Bucket: aws.String("BucketName"), // Required
	}
	resp, err := svc.PutBucketAccelerateConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketAcl() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketAclInput{
		Bucket: aws.String("BucketName"), // Required
		ACL:    aws.String("BucketCannedACL"),
		AccessControlPolicy: &storage.AccessControlPolicy{
			Grants: []*storage.Grant{
				{ // Required
					Grantee: &storage.Grantee{
						Type:         aws.String("Type"), // Required
						DisplayName:  aws.String("DisplayName"),
						EmailAddress: aws.String("EmailAddress"),
						ID:           aws.String("ID"),
						URI:          aws.String("URI"),
					},
					Permission: aws.String("Permission"),
				},
				// More values...
			},
			Owner: &storage.Owner{
				DisplayName: aws.String("DisplayName"),
				ID:          aws.String("ID"),
			},
		},
		ContentMD5:       aws.String("ContentMD5"),
		GrantFullControl: aws.String("GrantFullControl"),
		GrantRead:        aws.String("GrantRead"),
		GrantReadACP:     aws.String("GrantReadACP"),
		GrantWrite:       aws.String("GrantWrite"),
		GrantWriteACP:    aws.String("GrantWriteACP"),
	}
	resp, err := svc.PutBucketAcl(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketAnalyticsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketAnalyticsConfigurationInput{
		AnalyticsConfiguration: &storage.AnalyticsConfiguration{ // Required
			Id: aws.String("AnalyticsId"), // Required
			StorageClassAnalysis: &storage.ClassAnalysis{ // Required
				DataExport: &storage.ClassAnalysisDataExport{
					Destination: &storage.AnalyticsExportDestination{ // Required
						S3BucketDestination: &storage.AnalyticsS3BucketDestination{ // Required
							Bucket:          aws.String("BucketName"),                  // Required
							Format:          aws.String("AnalyticsS3ExportFileFormat"), // Required
							BucketAccountId: aws.String("AccountId"),
							Prefix:          aws.String("Prefix"),
						},
					},
					OutputSchemaVersion: aws.String("ClassAnalysisSchemaVersion"), // Required
				},
			},
			Filter: &storage.AnalyticsFilter{
				And: &storage.AnalyticsAndOperator{
					Prefix: aws.String("Prefix"),
					Tags: []*storage.Tag{
						{ // Required
							Key:   aws.String("ObjectKey"), // Required
							Value: aws.String("Value"),     // Required
						},
						// More values...
					},
				},
				Prefix: aws.String("Prefix"),
				Tag: &storage.Tag{
					Key:   aws.String("ObjectKey"), // Required
					Value: aws.String("Value"),     // Required
				},
			},
		},
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("AnalyticsId"), // Required
	}
	resp, err := svc.PutBucketAnalyticsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketCors() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketCorsInput{
		Bucket: aws.String("BucketName"), // Required
		CORSConfiguration: &storage.CORSConfiguration{ // Required
			CORSRules: []*storage.CORSRule{ // Required
				{ // Required
					AllowedMethods: []*string{ // Required
						aws.String("AllowedMethod"), // Required
						// More values...
					},
					AllowedOrigins: []*string{ // Required
						aws.String("AllowedOrigin"), // Required
						// More values...
					},
					AllowedHeaders: []*string{
						aws.String("AllowedHeader"), // Required
						// More values...
					},
					ExposeHeaders: []*string{
						aws.String("ExposeHeader"), // Required
						// More values...
					},
					MaxAgeSeconds: aws.Int64(1),
				},
				// More values...
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketCors(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketInventoryConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketInventoryConfigurationInput{
		Bucket: aws.String("BucketName"),  // Required
		Id:     aws.String("InventoryId"), // Required
		InventoryConfiguration: &storage.InventoryConfiguration{ // Required
			Destination: &storage.InventoryDestination{ // Required
				S3BucketDestination: &storage.InventoryS3BucketDestination{ // Required
					Bucket:    aws.String("BucketName"),      // Required
					Format:    aws.String("InventoryFormat"), // Required
					AccountId: aws.String("AccountId"),
					Prefix:    aws.String("Prefix"),
				},
			},
			Id: aws.String("InventoryId"), // Required
			IncludedObjectVersions: aws.String("InventoryIncludedObjectVersions"), // Required
			IsEnabled:              aws.Bool(true),                                // Required
			Schedule: &storage.InventorySchedule{ // Required
				Frequency: aws.String("InventoryFrequency"), // Required
			},
			Filter: &storage.InventoryFilter{
				Prefix: aws.String("Prefix"), // Required
			},
			OptionalFields: []*string{
				aws.String("InventoryOptionalField"), // Required
				// More values...
			},
		},
	}
	resp, err := svc.PutBucketInventoryConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketLifecycle() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketLifecycleInput{
		Bucket:     aws.String("BucketName"), // Required
		ContentMD5: aws.String("ContentMD5"),
		LifecycleConfiguration: &storage.LifecycleConfiguration{
			Rules: []*storage.Rule{ // Required
				{ // Required
					Prefix: aws.String("Prefix"),           // Required
					Status: aws.String("ExpirationStatus"), // Required
					AbortIncompleteMultipartUpload: &storage.AbortIncompleteMultipartUpload{
						DaysAfterInitiation: aws.Int64(1),
					},
					Expiration: &storage.LifecycleExpiration{
						Date: aws.Time(time.Now()),
						Days: aws.Int64(1),
						ExpiredObjectDeleteMarker: aws.Bool(true),
					},
					ID: aws.String("ID"),
					NoncurrentVersionExpiration: &storage.NoncurrentVersionExpiration{
						NoncurrentDays: aws.Int64(1),
					},
					NoncurrentVersionTransition: &storage.NoncurrentVersionTransition{
						NoncurrentDays: aws.Int64(1),
						StorageClass:   aws.String("TransitionStorageClass"),
					},
					Transition: &storage.Transition{
						Date:         aws.Time(time.Now()),
						Days:         aws.Int64(1),
						StorageClass: aws.String("TransitionStorageClass"),
					},
				},
				// More values...
			},
		},
	}
	resp, err := svc.PutBucketLifecycle(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketLifecycleConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketLifecycleConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
		LifecycleConfiguration: &storage.BucketLifecycleConfiguration{
			Rules: []*storage.LifecycleRule{ // Required
				{ // Required
					Status: aws.String("ExpirationStatus"), // Required
					AbortIncompleteMultipartUpload: &storage.AbortIncompleteMultipartUpload{
						DaysAfterInitiation: aws.Int64(1),
					},
					Expiration: &storage.LifecycleExpiration{
						Date: aws.Time(time.Now()),
						Days: aws.Int64(1),
						ExpiredObjectDeleteMarker: aws.Bool(true),
					},
					Filter: &storage.LifecycleRuleFilter{
						And: &storage.LifecycleRuleAndOperator{
							Prefix: aws.String("Prefix"),
							Tags: []*storage.Tag{
								{ // Required
									Key:   aws.String("ObjectKey"), // Required
									Value: aws.String("Value"),     // Required
								},
								// More values...
							},
						},
						Prefix: aws.String("Prefix"),
						Tag: &storage.Tag{
							Key:   aws.String("ObjectKey"), // Required
							Value: aws.String("Value"),     // Required
						},
					},
					ID: aws.String("ID"),
					NoncurrentVersionExpiration: &storage.NoncurrentVersionExpiration{
						NoncurrentDays: aws.Int64(1),
					},
					NoncurrentVersionTransitions: []*storage.NoncurrentVersionTransition{
						{ // Required
							NoncurrentDays: aws.Int64(1),
							StorageClass:   aws.String("TransitionStorageClass"),
						},
						// More values...
					},
					Prefix: aws.String("Prefix"),
					Transitions: []*storage.Transition{
						{ // Required
							Date:         aws.Time(time.Now()),
							Days:         aws.Int64(1),
							StorageClass: aws.String("TransitionStorageClass"),
						},
						// More values...
					},
				},
				// More values...
			},
		},
	}
	resp, err := svc.PutBucketLifecycleConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketLogging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketLoggingInput{
		Bucket: aws.String("BucketName"), // Required
		BucketLoggingStatus: &storage.BucketLoggingStatus{ // Required
			LoggingEnabled: &storage.LoggingEnabled{
				TargetBucket: aws.String("TargetBucket"),
				TargetGrants: []*storage.TargetGrant{
					{ // Required
						Grantee: &storage.Grantee{
							Type:         aws.String("Type"), // Required
							DisplayName:  aws.String("DisplayName"),
							EmailAddress: aws.String("EmailAddress"),
							ID:           aws.String("ID"),
							URI:          aws.String("URI"),
						},
						Permission: aws.String("BucketLogsPermission"),
					},
					// More values...
				},
				TargetPrefix: aws.String("TargetPrefix"),
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketLogging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketMetricsConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketMetricsConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
		Id:     aws.String("MetricsId"),  // Required
		MetricsConfiguration: &storage.MetricsConfiguration{ // Required
			Id: aws.String("MetricsId"), // Required
			Filter: &storage.MetricsFilter{
				And: &storage.MetricsAndOperator{
					Prefix: aws.String("Prefix"),
					Tags: []*storage.Tag{
						{ // Required
							Key:   aws.String("ObjectKey"), // Required
							Value: aws.String("Value"),     // Required
						},
						// More values...
					},
				},
				Prefix: aws.String("Prefix"),
				Tag: &storage.Tag{
					Key:   aws.String("ObjectKey"), // Required
					Value: aws.String("Value"),     // Required
				},
			},
		},
	}
	resp, err := svc.PutBucketMetricsConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketNotification() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketNotificationInput{
		Bucket: aws.String("BucketName"), // Required
		NotificationConfiguration: &storage.NotificationConfigurationDeprecated{ // Required
			CloudFunctionConfiguration: &storage.CloudFunctionConfiguration{
				CloudFunction: aws.String("CloudFunction"),
				Event:         aws.String("Event"),
				Events: []*string{
					aws.String("Event"), // Required
					// More values...
				},
				Id:             aws.String("NotificationId"),
				InvocationRole: aws.String("CloudFunctionInvocationRole"),
			},
			QueueConfiguration: &storage.QueueConfigurationDeprecated{
				Event: aws.String("Event"),
				Events: []*string{
					aws.String("Event"), // Required
					// More values...
				},
				Id:    aws.String("NotificationId"),
				Queue: aws.String("QueueArn"),
			},
			TopicConfiguration: &storage.TopicConfigurationDeprecated{
				Event: aws.String("Event"),
				Events: []*string{
					aws.String("Event"), // Required
					// More values...
				},
				Id:    aws.String("NotificationId"),
				Topic: aws.String("TopicArn"),
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketNotification(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketNotificationConfiguration() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketNotificationConfigurationInput{
		Bucket: aws.String("BucketName"), // Required
		NotificationConfiguration: &storage.NotificationConfiguration{ // Required
			LambdaFunctionConfigurations: []*storage.LambdaFunctionConfiguration{
				{ // Required
					Events: []*string{ // Required
						aws.String("Event"), // Required
						// More values...
					},
					LambdaFunctionArn: aws.String("LambdaFunctionArn"), // Required
					Filter: &storage.NotificationConfigurationFilter{
						Key: &storage.S3KeyFilter{
							FilterRules: []*storage.FilterRule{
								{ // Required
									Name:  aws.String("FilterRuleName"),
									Value: aws.String("FilterRuleValue"),
								},
								// More values...
							},
						},
					},
					Id: aws.String("NotificationId"),
				},
				// More values...
			},
			QueueConfigurations: []*storage.QueueConfiguration{
				{ // Required
					Events: []*string{ // Required
						aws.String("Event"), // Required
						// More values...
					},
					QueueArn: aws.String("QueueArn"), // Required
					Filter: &storage.NotificationConfigurationFilter{
						Key: &storage.S3KeyFilter{
							FilterRules: []*storage.FilterRule{
								{ // Required
									Name:  aws.String("FilterRuleName"),
									Value: aws.String("FilterRuleValue"),
								},
								// More values...
							},
						},
					},
					Id: aws.String("NotificationId"),
				},
				// More values...
			},
			TopicConfigurations: []*storage.TopicConfiguration{
				{ // Required
					Events: []*string{ // Required
						aws.String("Event"), // Required
						// More values...
					},
					TopicArn: aws.String("TopicArn"), // Required
					Filter: &storage.NotificationConfigurationFilter{
						Key: &storage.S3KeyFilter{
							FilterRules: []*storage.FilterRule{
								{ // Required
									Name:  aws.String("FilterRuleName"),
									Value: aws.String("FilterRuleValue"),
								},
								// More values...
							},
						},
					},
					Id: aws.String("NotificationId"),
				},
				// More values...
			},
		},
	}
	resp, err := svc.PutBucketNotificationConfiguration(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketPolicy() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketPolicyInput{
		Bucket:     aws.String("BucketName"), // Required
		Policy:     aws.String("Policy"),     // Required
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketPolicy(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketReplication() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketReplicationInput{
		Bucket: aws.String("BucketName"), // Required
		ReplicationConfiguration: &storage.ReplicationConfiguration{ // Required
			Role: aws.String("Role"), // Required
			Rules: []*storage.ReplicationRule{ // Required
				{ // Required
					Destination: &storage.Destination{ // Required
						Bucket:       aws.String("BucketName"), // Required
						StorageClass: aws.String("Class"),
					},
					Prefix: aws.String("Prefix"),                // Required
					Status: aws.String("ReplicationRuleStatus"), // Required
					ID:     aws.String("ID"),
				},
				// More values...
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketReplication(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketRequestPayment() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketRequestPaymentInput{
		Bucket: aws.String("BucketName"), // Required
		RequestPaymentConfiguration: &storage.RequestPaymentConfiguration{ // Required
			Payer: aws.String("Payer"), // Required
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketRequestPayment(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketTaggingInput{
		Bucket: aws.String("BucketName"), // Required
		Tagging: &storage.Tagging{ // Required
			TagSet: []*storage.Tag{ // Required
				{ // Required
					Key:   aws.String("ObjectKey"), // Required
					Value: aws.String("Value"),     // Required
				},
				// More values...
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketVersioning() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketVersioningInput{
		Bucket: aws.String("BucketName"), // Required
		VersioningConfiguration: &storage.VersioningConfiguration{ // Required
			MFADelete: aws.String("MFADelete"),
			Status:    aws.String("BucketVersioningStatus"),
		},
		ContentMD5: aws.String("ContentMD5"),
		MFA:        aws.String("MFA"),
	}
	resp, err := svc.PutBucketVersioning(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutBucketWebsite() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutBucketWebsiteInput{
		Bucket: aws.String("BucketName"), // Required
		WebsiteConfiguration: &storage.WebsiteConfiguration{ // Required
			ErrorDocument: &storage.ErrorDocument{
				Key: aws.String("ObjectKey"), // Required
			},
			IndexDocument: &storage.IndexDocument{
				Suffix: aws.String("Suffix"), // Required
			},
			RedirectAllRequestsTo: &storage.RedirectAllRequestsTo{
				HostName: aws.String("HostName"), // Required
				Protocol: aws.String("Protocol"),
			},
			RoutingRules: []*storage.RoutingRule{
				{ // Required
					Redirect: &storage.Redirect{ // Required
						HostName:             aws.String("HostName"),
						HttpRedirectCode:     aws.String("HttpRedirectCode"),
						Protocol:             aws.String("Protocol"),
						ReplaceKeyPrefixWith: aws.String("ReplaceKeyPrefixWith"),
						ReplaceKeyWith:       aws.String("ReplaceKeyWith"),
					},
					Condition: &storage.Condition{
						HttpErrorCodeReturnedEquals: aws.String("HttpErrorCodeReturnedEquals"),
						KeyPrefixEquals:             aws.String("KeyPrefixEquals"),
					},
				},
				// More values...
			},
		},
		ContentMD5: aws.String("ContentMD5"),
	}
	resp, err := svc.PutBucketWebsite(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutObjectInput{
		Bucket:             aws.String("BucketName"), // Required
		Key:                aws.String("ObjectKey"),  // Required
		ACL:                aws.String("ObjectCannedACL"),
		Body:               []byte("PAYLOAD"),
		CacheControl:       aws.String("CacheControl"),
		ContentDisposition: aws.String("ContentDisposition"),
		ContentEncoding:    aws.String("ContentEncoding"),
		ContentLanguage:    aws.String("ContentLanguage"),
		ContentLength:      aws.Int64(1),
		ContentMD5:         aws.String("ContentMD5"),
		ContentType:        aws.String("ContentType"),
		Expires:            aws.Time(time.Now()),
		GrantFullControl:   aws.String("GrantFullControl"),
		GrantRead:          aws.String("GrantRead"),
		GrantReadACP:       aws.String("GrantReadACP"),
		GrantWriteACP:      aws.String("GrantWriteACP"),
		Metadata: map[string]*string{
			"Key": aws.String("MetadataValue"), // Required
			// More values...
		},
		RequestPayer:            aws.String("RequestPayer"),
		SSECustomerAlgorithm:    aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:          aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:       aws.String("SSECustomerKeyMD5"),
		SSEKMSKeyId:             aws.String("SSEKMSKeyId"),
		ServerSideEncryption:    aws.String("ServerSideEncryption"),
		StorageClass:            aws.String("Class"),
		Tagging:                 aws.String("TaggingHeader"),
		WebsiteRedirectLocation: aws.String("WebsiteRedirectLocation"),
	}
	resp, err := svc.PutObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutObjectAcl() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutObjectAclInput{
		Bucket: aws.String("BucketName"), // Required
		Key:    aws.String("ObjectKey"),  // Required
		ACL:    aws.String("ObjectCannedACL"),
		AccessControlPolicy: &storage.AccessControlPolicy{
			Grants: []*storage.Grant{
				{ // Required
					Grantee: &storage.Grantee{
						Type:         aws.String("Type"), // Required
						DisplayName:  aws.String("DisplayName"),
						EmailAddress: aws.String("EmailAddress"),
						ID:           aws.String("ID"),
						URI:          aws.String("URI"),
					},
					Permission: aws.String("Permission"),
				},
				// More values...
			},
			Owner: &storage.Owner{
				DisplayName: aws.String("DisplayName"),
				ID:          aws.String("ID"),
			},
		},
		ContentMD5:       aws.String("ContentMD5"),
		GrantFullControl: aws.String("GrantFullControl"),
		GrantRead:        aws.String("GrantRead"),
		GrantReadACP:     aws.String("GrantReadACP"),
		GrantWrite:       aws.String("GrantWrite"),
		GrantWriteACP:    aws.String("GrantWriteACP"),
		RequestPayer:     aws.String("RequestPayer"),
		VersionId:        aws.String("ObjectVersionId"),
	}
	resp, err := svc.PutObjectAcl(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_PutObjectTagging() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.PutObjectTaggingInput{
		Bucket: aws.String("BucketName"), // Required
		Key:    aws.String("ObjectKey"),  // Required
		Tagging: &storage.Tagging{ // Required
			TagSet: []*storage.Tag{ // Required
				{ // Required
					Key:   aws.String("ObjectKey"), // Required
					Value: aws.String("Value"),     // Required
				},
				// More values...
			},
		},
		ContentMD5: aws.String("ContentMD5"),
		VersionId:  aws.String("ObjectVersionId"),
	}
	resp, err := svc.PutObjectTagging(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_RestoreObject() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.RestoreObjectInput{
		Bucket:       aws.String("BucketName"), // Required
		Key:          aws.String("ObjectKey"),  // Required
		RequestPayer: aws.String("RequestPayer"),
		RestoreRequest: &storage.RestoreRequest{
			Days: aws.Int64(1), // Required
			GlacierJobParameters: &storage.GlacierJobParameters{
				Tier: aws.String("Tier"), // Required
			},
		},
		VersionId: aws.String("ObjectVersionId"),
	}
	resp, err := svc.RestoreObject(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_UploadPart() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.UploadPartInput{
		Bucket:               aws.String("BucketName"),        // Required
		Key:                  aws.String("ObjectKey"),         // Required
		PartNumber:           aws.Int64(1),                    // Required
		UploadId:             aws.String("MultipartUploadId"), // Required
		Body:                 []byte("PAYLOAD"),
		ContentLength:        aws.Int64(1),
		ContentMD5:           aws.String("ContentMD5"),
		RequestPayer:         aws.String("RequestPayer"),
		SSECustomerAlgorithm: aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:       aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:    aws.String("SSECustomerKeyMD5"),
	}
	resp, err := svc.UploadPart(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}

func Examplestorage_UploadPartCopy() {
	sess := session.Must(session.NewSession())

	svc := storage.New(sess)

	params := &storage.UploadPartCopyInput{
		Bucket:                         aws.String("BucketName"),        // Required
		CopySource:                     aws.String("CopySource"),        // Required
		Key:                            aws.String("ObjectKey"),         // Required
		PartNumber:                     aws.Int64(1),                    // Required
		UploadId:                       aws.String("MultipartUploadId"), // Required
		CopySourceIfMatch:              aws.String("CopySourceIfMatch"),
		CopySourceIfModifiedSince:      aws.Time(time.Now()),
		CopySourceIfNoneMatch:          aws.String("CopySourceIfNoneMatch"),
		CopySourceIfUnmodifiedSince:    aws.Time(time.Now()),
		CopySourceRange:                aws.String("CopySourceRange"),
		CopySourceSSECustomerAlgorithm: aws.String("CopySourceSSECustomerAlgorithm"),
		CopySourceSSECustomerKey:       aws.String("CopySourceSSECustomerKey"),
		CopySourceSSECustomerKeyMD5:    aws.String("CopySourceSSECustomerKeyMD5"),
		RequestPayer:                   aws.String("RequestPayer"),
		SSECustomerAlgorithm:           aws.String("SSECustomerAlgorithm"),
		SSECustomerKey:                 aws.String("SSECustomerKey"),
		SSECustomerKeyMD5:              aws.String("SSECustomerKeyMD5"),
	}
	resp, err := svc.UploadPartCopy(params)

	if err != nil {
		// Print the error, cast err to awserr.Error to get the Code and
		// Message from an error.
		fmt.Println(err.Error())
		return
	}

	// Pretty-print the response data.
	fmt.Println(resp)
}
